<!-- FOOTER -->
<footer>
    <div class=" footer">
        <div class="container">
            <div class="links">
                <ul class="links-footer">
                    <li>Contact Us</li>
                    <li>estore</li>
                    <li>Career center</li>
                    <li>Reports</li>
                    <li>results</li>
                </ul></div>

            <div  class="social">
                <ul class="list-inline">

                    <li><a href="#" class="icoFacebook fa-2x" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="icoTwitter fa-2x" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" class="icoGoogle fa-2x" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#" class="icoLinkedin fa-2x" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                </ul></div>
            <div class="clearfix"></div>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy;2016 All right reseved   &middot; <a href="#">certigate pro</a></p>
        </div>
    </div> 
</footer>

