{{$headerContainer}}
<!-- bluebar-->
<div class="main-nav navbar-fixed-top">
    <div class="blue-wrapper navbar-inverse">
        <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bar" aria-expanded="false" aria-controls="bar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div id="bar" class="navbar-collapse collapse navbar-right">
                {{^loggedInUsername}}
                <div id="bar" class="navbar-collapse collapse">
                    <form name="signin_header_form" method="post" action="/sign/in" class="navbar-form navbar-right">
                        <div class="form-group">
                            <input name="username" type="text" placeholder="Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <input name="password" type="password" placeholder="Password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </form>
                </div>
                {{/loggedInUsername}}
                {{#loggedInUsername}}
                <div class="navbar-form navbar-right">
                    {{! IMPORTANT: links style attribute is temporary }}
                    <div class="form-group"><a style="color:#fff" href="#"><span class="glyphicon glyphicon-user"></span> {{loggedInUsername}}</a></div>
                    &nbsp;
                    <div class="form-group"><a style="color:#fff" href="/sign/out"><span class="glyphicon glyphicon-log-out"></span> Log out</a></div>
                </div>
                {{/loggedInUsername}}

            </div><!--/.navbar-collapse -->
        </div>
    </div>
    <!-- endbluebar-->

    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse white-bar">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><img src="/images/logo.png" width="223" height="65" alt=""/></a>
                    </div>
                    <div>
                        {{{adminMenu}}}
                    </div>
                    <div>
                        {{{primaryMenu}}}
                    </div>
                </div>
            </nav>

        </div>
    </div>
</div>
{{/headerContainer}}
