<!-- bluebar-->
<div class="main-nav navbar-fixed-top">
    <div class="blue-wrapper navbar-inverse ">
        <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bar" aria-expanded="false" aria-controls="bar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div id="bar" class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav navbar-right">
                    {{^loggedInUsername}}
                    <li><a href="/sign/in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    {{/loggedInUsername}}
                    {{#loggedInUsername}}
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{loggedInUsername}}</a></li>
                    <li><a href="/sign/out"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                    {{/loggedInUsername}}
                </ul>
            </div><!--/.navbar-collapse -->
        </div>
    </div>
    <!-- endbluebar-->

    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse white-bar">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><img src="/images/logo.png" width="223" height="65" alt=""/></a>
                    </div>
                    {{! {primaryMenu} !}}

                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">

                            <li><a href="#about">About</a></li>
                            <li><a href="courses.html">Training & Certification</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li><a href="#contact">partnership</a></li>
                            <li><a href="#contact"> instructors</a></li>
                            <li><a href="#contact">Estore  reports</a></li>
                            <li><a href="#contact">  reports</a></li>

                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </div>
</div>

