{{% BLOCKS }}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/concat/app.css" rel="stylesheet" type="text/css"/>
        <title>{{$title}}Certigate Pro{{/title}}</title>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}
    </head>

    <body>
        {{>header}}

        <div class="main-holder">
            {{>messages}}
            {{$content}}{{/content}}  
            {{>footer}}
        </div>

        <script src="/concat/app.js" type="text/javascript"></script>
        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}
    </body>
</html>
