<?php

require_once __DIR__ . '/../AbstractSeed.php';

use db\AbstractSeed;
use \Users\Entity\User;
use Users\Entity\Role;
use Utilities\Service\Time;

class PosAUsers extends AbstractSeed
{

    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $faker = Faker\Factory::create();

        $adminRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::ADMIN_ROLE));
        $TMRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::TRAINING_MANAGER_ROLE));
        $TCARole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::TEST_CENTER_ADMIN_ROLE));
        $instructorRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::INSTRUCTOR_ROLE));
        $studentRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::STUDENT_ROLE));
        $distributorRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::DISTRIBUTOR_ROLE));
        $resellerRole = $this->serviceManager->get("wrapperQuery")->findOneBy("Users\Entity\Role", array("name" => Role::RESELLER_ROLE));

        $adminUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "admin",
            "password" => "adminadmin",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->word . $faker->freeEmail, //increase mail randomness to avoid duplicate mails when faker fails generating same mail multiple times
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $adminRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );

        $userModel = $this->serviceManager->get("Users\Model\User");
        $userModel->saveUser($adminUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);
        $normalUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "user",
            "password" => "useruser",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($normalUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $TMUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "tmuser",
            "password" => "tmuser",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => true,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $TMRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($TMUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);
        // test center admin
        $TCAUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "tcauser",
            "password" => "tcauser",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => true,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $TCARole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($TCAUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);


        $instructorUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "instructor",
            "password" => "instructor",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => true,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $instructorRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($instructorUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $studentUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "student",
            "password" => "student",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => true,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $studentRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($studentUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $TMUser2 = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "tmuser2",
            "password" => "tmuser2",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => true,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $TMRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($TMUser2, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        // test center admin
        $TCAUser2 = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "tcauser2",
            "password" => "tcauser2",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => true,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $TCARole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($TCAUser2, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $resellerUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "reseller",
            "password" => "reseller",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => true,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $resellerRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($resellerUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $resellerUser2 = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "reseller2",
            "password" => "reseller2",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => true,
            "distributorStatement" => false,
            "status" => true,
            "roles" => array(
                $resellerRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($resellerUser2, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $DistributorUser = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "distributor",
            "password" => "distributor",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => true,
            "status" => true,
            "roles" => array(
                $distributorRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($DistributorUser, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);

        $DistributorUser2 = array(
            "firstName" => $faker->firstName,
            "firstNameAr" => $faker->firstName,
            "middleName" => $faker->name,
            "middleNameAr" => $faker->name,
            "lastName" => $faker->lastName,
            "lastNameAr" => $faker->lastName,
            "country" => $faker->countryCode,
            "language" => $faker->languageCode,
            "username" => "distributor2",
            "password" => "distributor2",
            "mobile" => "555-555-5555",
            "addressOne" => $faker->address,
            "addressOneAr" => $faker->address,
            "addressTwo" => $faker->address,
            "addressTwoAr" => $faker->address,
            "city" => $faker->city,
            "zipCode" => $faker->postcode,
            "phone" =>"555-555-5555",
            "nationality" => $faker->countryCode,
            "identificationType" => $faker->word,
            "identificationNumber" => $faker->numberBetween(/* $min = */ 999999),
            "identificationExpiryDate" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "identificationExpiryDateHj" => $faker->dateTimeBetween(/* $startDate = */ '+2 years', /* $endDate = */ '+20 years')->format(Time::DATE_FORMAT),
            "email" => $faker->freeEmail,
            "securityQuestion" => $faker->sentence,
            "securityAnswer" => $faker->sentence,
            "dateOfBirth" => date(Time::DATE_FORMAT),
            "dateOfBirthHj" => date(Time::DATE_FORMAT),
            "photo" => '/upload/images/userdefault.png',
            "privacyStatement" => true,
            "studentStatement" => false,
            "proctorStatement" => false,
            "instructorStatement" => false,
            "testCenterAdministratorStatement" => false,
            "trainingManagerStatement" => false,
            "resellerStatement" => false,
            "distributorStatement" => true,
            "status" => true,
            "roles" => array(
                $distributorRole->getId()
            ),
            'longitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
            'latitude' => $faker->randomFloat(/* $nbMaxDecimals = */ 5, /* $min = */ 111111, /* $max = */ 999999),
        );
        $userModel->saveUser($DistributorUser2, /* $userObj = */ new User(), /* $isAdminUser = */ true, /* $editFormFlag = */ false);
    }

}
