{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Manage Proctors{{/translate}}</h3>
    </div>
    <!--    <div class="panel-body">
            {{{examBookProctorForm}}}
        </div>-->
    <div class="panel-body main-form  ">
        {{{openTag}}}
        <div class="row panel-border">
            <h2 class="sub-title-form"> ATC PROCTORS </h2>
            <div class="col-md-12">
                <div class="form-group">
                    <div class="row roles-inputs">
                        {{{proctors}}}
                        {{{proctorsError}}}
                    </div>
                </div>
            </div>

            <input type="Submit" name="buttons[create]" class="pull-left btn-inline btn btn-success" value="Save">
            <input name="buttons[reset]" class="pull-left btn-inline btn btn-danger resetButton" type="button" value="Reset"></fieldset>
        </div>
        {{{closeTag}}}
    </div>

</div>
{{/content}}
{{/layout}}
