{{% BLOCKS }}
{{<layout}}
{{$content}}

<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Exam Requests{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Course name{{/translate}}</th>
                <th>{{#translate}}Authorized Testing Center{{/translate}}</th>
                <th>{{#translate}}Exam Date{{/translate}}</th>
                <th>{{#translate}}Hijri Exam Date{{/translate}}</th>
                <th>{{#translate}}Students No.{{/translate}}</th>
                <th>{{#translate}}Admin Status{{/translate}}</th>
                <th>{{#translate}}TVTC Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#requests}}
            <tr>
                <td>{{course.name}}</td>
                <td>{{atc.commercialName}}</td>
                <td>{{date}}</td>
                <td>{{dateHj}}</td>
                <td>{{studentsNo}}</td>
                {{#isAdminPending}}
                <td><span class="error">{{adminStatus}}</span></td>
                {{/isAdminPending}}
                {{^isAdminPending}}
                <td><span>{{adminStatus}}</span></td>
                {{/isAdminPending}}
                
                {{#isTvtcPending}}
                <td><span class="error">{{tvtcStatus}}</span></td>
                {{/isTvtcPending}}
                {{^isTvtcPending}}
                <td><span>{{tvtcStatus}}</span></td>
                {{/isTvtcPending}}
                <td>
                    <a href="/courses/exam/proctors/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Proctors{{/translate}}"><span class="glyphicon glyphicon-user"></span></a>
                    {{#isAdminUser}}
                        {{#isAdminPending}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/courses/exam/request/accept/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Accept{{/translate}}"><span class="glyphicon glyphicon-ok"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/courses/exam/request/decline/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                        {{/isAdminPending}}
                    {{/isAdminUser}}
                </td>
            </tr>
            {{/requests}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
