Dear {{user.firstName}} {{user.lastName}},

<br>
<br>
{{#translate}}Check our new press release{{/translate}};

{{#pressRelease}}
<div>
    <div>
        <div>
            <h4>{{title}}</h4><p>By {{author}}</p>
            <p>{{summary}}</p>
            <ul>
                <a href="{{pressReleaseUrl}}" target="_blank"> {{#translate}}Read more{{/translate}} ...</a>
            </ul>
        </div>
        <hr>
    </div>
</div>
{{/pressRelease}}

If you want to unsubscribe, <a href="{{unsubscribeUrl}}" target="_blank">{{#translate}}Click here{{/translate}}</a>