{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit User</h3>
                 <img src="{{photo}}" data-toggle="tooltip" data-placement="left"  class="user-photos" style="height: 70px !important;width: 70px !important;">
    </div>
    <div class="panel-body register">
        {{{userForm}}}
    </div>
</div>
{{/content}}

{{$scripts}}
<script>
    $(document).ready(function () {
        {{#rolesStatements}}   
                generateStatementCheckboxContent('user_form_agreements_{{type}}', '{{title}}', '{{{sentence}}}', '{{{content}}}', '{{role}}');
        {{/rolesStatements}}
        {{#privacyStatement}}
                generateStatementCheckboxContent('user_form_privacyStatement', '{{title}}', '{{{sentence}}}', '{{{content}}}', '{{role}}');
        {{/privacyStatement}}
        
            {{#success}}
            
            if({{success}}){
                alert('Saved Successfully');
            }
            
            {{/success}}
            
            
            });
</script>
{{/scripts}}
{{/layout}}
