{{% BLOCKS }}
{{<layout}}
{{$content}}

<div class="panel panel-default">

    <div class="panel-heading">
        {{#translate}}Instructors{{/translate}}
    </div>

    <!-- Table -->
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>{{#translate}}Photo{{/translate}}</th>
                    <th>{{#translate}}First Name{{/translate}}</th>
                    <th>{{#translate}}Last Name{{/translate}}</th>
                    <th>{{#translate}}User Name{{/translate}}</th>
                    <th>{{#translate}}Email{{/translate}}</th>
                    <th>{{#translate}}Country{{/translate}}</th>
                    <th colspan="2">{{#translate}}Actions{{/translate}}</th>
                </tr>
            </thead>
            <tbody>
                {{#users}}
                <tr>
                    <th scope="row"><img src="{{photo}}" data-toggle="tooltip" data-placement="left" title="{{name}}" class="user-photos" style="height: 70px !important;width: 70px !important;"></th>
                    <td>
                        {{#locale_en}}
                        {{firstName}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{firstNameAr}}
                        {{/locale_ar}}        
                    </td>
                    <td>
                        {{#locale_en}}
                        {{lastName}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{lastNameAr}}
                        {{/locale_ar}}        
                    </td>
                    <td>{{username}}</td>
                    <td>{{email}}</td>
                    <td>{{countryText}}</td>
                    <td>
                        <a data-toggle="tooltip" data-placement="left" title="{{#translate}}More{{/translate}}" href="/users/more/{{id}}"><span class="glyphicon glyphicon-plus"></span></a>
                    </td>
                </tr>
                {{/users}}
            </tbody>
        </table>
    </div>

</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > {{#translate}}Pages{{/translate}} :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}

{{/layout}}
