{{% BLOCKS }}
{{<layout}}
{{$content}}

<div class="panel panel-default">

    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <h3>{{#translate}}User Details{{/translate}}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <img src="{{user.0.photo}}" data-toggle="tooltip" data-placement="left"  class="user-photos" style="height: 70px !important;width: 70px !important;">
            </div>
            <div class="col-md-3">
                <a href="/users/edit/{{user.0.id}}"><button class="btn btn-info">Edit your profile</button></a>   
            </div>
        </div>

    </div>

    <!-- Table -->
    <div class="table-responsive">
        <table class="table">
            <tbody>
                {{#user}}
                <tr>
                    <td>{{#translate}}First Name{{/translate}}</td><td>{{firstName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}First Name in Arabic{{/translate}}</td><td>{{firstNameAr}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Middle Name{{/translate}}</td><td>{{middleName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Middle Name in Arabic{{/translate}}</td><td>{{middleNameAr}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Last Name{{/translate}}</td><td>{{lastName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Last Name in Arabic{{/translate}}</td><td>{{lastNameAr}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Phone{{/translate}}</td><td>{{phone}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}City{{/translate}}</td><td>{{city}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Country{{/translate}}</td><td>{{countryText}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Nationality{{/translate}}</td><td>{{nationalityText}}</td>
                </tr>
                {{/user}}
            </tbody>
        </table>
    </div>

</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > {{#translate}}Pages{{/translate}} :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}

{{/layout}}
