{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/issues/categories/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Category{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Categories{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Title{{/translate}}</th>
                <th>{{#translate}}Description{{/translate}}</th>
                <th>{{#translate}}Parent{{/translate}}</th>
                <th>{{#translate}}Weight{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#categories}}
            <tr>
                <td>{{title}}</td>
                <td>{{description}}</td>
                <td>{{parent}}</td>
                <td>{{weight}}</td>
                <td>
                    <a href="/issues/categories/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#hasChildren}}
                    <a  class="delete_row"  onclick="deleteParentCategory(true, {{id}})"data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/hasChildren}}
                    {{^hasChildren}}
                    <a  class="delete_row"  onclick="deleteParentCategory(false, {{id}})"data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/hasChildren}}
                </td>
            </tr>
            {{/categories}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{$scripts}}
<script type="text/javascript">
    /**
     * function to delete categories
     * @param boolean hasChildren if category has children or not 
     * @param int id category id 
     */
    function deleteParentCategory(hasChildren, id) {
        message= '';
        (hasChildren)? message="{{#translate}}This category may have sub-Categories{{/translate}}" : message="{{#translate}}This category has No sub-Categories{{/translate}}" ;
        bootbox.confirm(message+" ...?", function (result) {
            if (result) {
                window.location.assign('/issues/categories/remove/'+id);
            }
        });
    }
</script>
{{/scripts}}
{{/layout}}

