{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Edit Issues Category{{/translate}}</h3>
    </div>
    <div class="panel-body main-form  ">
        {{{openTag}}}
        <div class="row panel-border">
            <h2 class="sub-title-form"> CATEGORY DATA</h2>
            {{{id}}}
            <div class="col-md-6">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="issues_categories_form_title">{{titleLabel}}</label>
                    <div class="col-sm-9">
                        {{{title}}}
                        {{{titleError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="issues_categories_form_description">{{descriptionLabel}}</label>
                    <div class="col-sm-9">
                        {{{description}}}
                        {{{descriptionError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="issues_categories_form_email">{{emailLabel}}</label>
                    <div class="col-sm-9">
                        {{{email}}}
                        {{{emailError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="issues_categories_form_weight">{{weightLabel}}</label>
                    <div class="col-sm-9">
                        {{{weight}}}
                        {{{weightError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="issues_categories_form_parent">{{parentLabel}}</label>
                    <div class="col-sm-9">
                        {{{parent}}}
                        {{{parentError}}}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{{id}}}
                {{{idError}}}
            </div>
            <input type="Submit" name="buttons[create]" class="pull-left btn-inline btn btn-success" value="Save">
            <input name="buttons[reset]" class="pull-left btn-inline btn btn-danger resetButton" type="button" value="Reset"></fieldset>
        </div>
        {{{closeTag}}}
    </div>
</div><!-- panel -->

{{/content}}
{{/layout}}
