{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .main-holder{
        margin-top: 0px;
    }
</style>
<!-- /.main holder -->
<div class="main-holder">
    <div class="container">
        <div class="page-container">
            <h3 class="sub-title-main">{{#translate}}Courses Calendar{{/translate}}</h3>
            {{#courses.count}}
            <div class="pull-right">
                <a class="btn btn-success" target="_blank" href="/quote/training/public">{{#translate}}Public Training{{/translate}}</a>
                <a class="btn btn-success" target="_blank" href="/quote/training/private">{{#translate}}Private Training{{/translate}}</a>
            </div>
            <div class="clearfix"></div>
            {{/courses.count}}

            <div class="row">
                {{#courses}}
                <div class="col-md-12 col-md-offset-0 calendar-box">
                    <a class="fa fa-cloud-download  calendar-download" aria-hidden="true" href="/courses/outlines/generate-pdf/{{id}}" title="{{#translate}}Download Outlines{{/translate}}"></a>
                    <h3 class="title-calendar">
                        {{#locale_en}}
                        {{name}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{nameAr}}
                        {{/locale_ar}}
                    </h3>
                    <p>
                        {{#locale_en}}
                        {{brief}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{briefAr}}
                        {{/locale_ar}}
                        <a href="/courses/more/{{id}}"> More</a>
                    </p>
                    {{#courseEvents}}
                    {{^hideFromCalendar}}
                    {{^alreadyStarted}}
                    <div class="calendar-list">
                        <ul class="">
                            <li class="course-dates">
                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                                {{#translate}}Starts at {{/translate}} {{startDate}} {{#translate}}to{{/translate}} {{endDate}}</a> 									
                            </li>
                            <li class="atp-name">
                                <a class="course-event-data" href="/organizations/more/{{atp.id}}" 
                                   title="{{#translate}}ATP Organization{{/translate}}">
                                    {{#locale_en}}
                                    {{atp.commercialName}}
                                    {{/locale_en}}
                                    {{#locale_ar}}
                                    {{atp.commercialNameAr}}
                                    {{/locale_ar}}
                                </a>
                            </li>
                            <li class="city-name">
                                <p class="course-event-data" 
                                   title="{{#translate}}City{{/translate}}">
                                    {{#locale_en}}
                                    {{atp.city}}
                                    {{/locale_en}}
                                    {{#locale_ar}}
                                    {{atp.cityAr}}
                                    {{/locale_ar}}
                                </p>
                            </li>
                            <li class="">
                                <span class=" addtocalendar atc-style-blue" data-on-calendar-click="atcOnCalendarClick" data-calendars="Google Calendar, Outlook">
                                    <a class="fa fa-calendar atcb-link"></a>
                                    <var class="atc_event">
                                        <var class="atc_date_start">{{startDateIso}}</var>
                                        <var class="atc_date_end">{{endDateIso}}</var>
                                        <var class="atc_timezone">{{timeZone}}</var>
                                        <var class="atc_title">{{course.name}}</var>
                                        <var class="atc_description">{{course.brief}}</var>
                                        <var class="atc_location">{{atp.city}}</var>
                                        <var class="atc_organizer">{{atp.commercialName}}</var>
                                        <var class="atc_organizer_email">{{atp.email}}.com</var>
                                    </var>
                                </span>
                            </li>
                            <li class="">
                                {{{formView}}} 
                            </li>
                            <li class="">
                                <!--<button type="button" class="btn btn-enroll-calendar">Enroll</button>-->
                                {{#canEnroll}}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="/courses/enroll/{{id}}"><button class="btn btn-small btn-enroll-calendar">{{#translate}}Enroll{{/translate}}</button></a>
                                {{/canEnroll}}
                                {{#canLeave}}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="/courses/leave/{{id}}"><button class="btn btn-small btn-cancel-calendar">{{#translate}}Cancel{{/translate}}</button></a>
                                {{/canLeave}}
                                {{#isFull}}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                {{#translate}}Course Full{{/translate}}
                                {{/isFull}}
                            </li>
                        </ul>
                    </div>
                    {{/alreadyStarted}}
                    {{/hideFromCalendar}}
                    {{/courseEvents}}
                </div>
                {{/courses}}
            </div>
        </div>
    </div>
    {{#hasPages}}
    <div class="pagination-bar">
        <p > Pages :  </p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <ul class="pagination">
            {{#previousPageNumber}}
            <li >
                <a href="?page={{previousPageNumber}}"><span class="glyphicon glyphicon-menu-left"></span></a>
            </li>
            {{/previousPageNumber}}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{#pageNumbers}}
            <li {{#isCurrent}}class="active"{{/isCurrent}} >
                <a href="?page={{pageNumber}}">{{pageNumber}}</a>
            </li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{/pageNumbers}}
            {{#nextPageNumber}}
            <li >
                <a href="?page={{nextPageNumber}}"><span class="glyphicon glyphicon-menu-right"></span></a>
            </li>
            {{/nextPageNumber}}
        </ul>
    </div>

    {{/hasPages}}

    <!-- /.main holder -->

    {{/content}}
    {{/layout}}