{{% BLOCKS }}
{{<layout}}

{{$content}}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#courseDetails" aria-controls="courseDetails" role="tab" data-toggle="tab">{{#translate}}Course Details{{/translate}}</a></li>
    <li role="presentation"><a href="/courses/evaluation/edit/{{courseId}}" aria-controls="courseEvaluation">{{#translate}}Course Evaluation{{/translate}}</a></li>
    <li role="presentation"><a href="/courses/resources/edit/{{courseId}}" aria-controls="courseResources">{{#translate}}Course Resources{{/translate}}</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="courseDetails">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{#translate}}Edit Course{{/translate}}</h3>
            </div>
            <div class="panel-body main-form  ">
                {{{openTag}}}
                <div class="row panel-border">
                    <h2 class="sub-title-form"> COURSE DATA</h2>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_name">{{nameLabel}}</label>
                            <div class="col-sm-10">
                                {{{name}}}
                                {{{nameError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_nameAr">{{nameArLabel}}</label>
                            <div class="col-sm-10">
                                {{{nameAr}}}
                                {{{nameArError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_brief">{{briefLabel}}</label>
                            <div class="col-sm-10">
                                {{{brief}}}
                                {{{briefError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_briefAr">{{briefArLabel}}</label>
                            <div class="col-sm-10">
                                {{{briefAr}}}
                                {{{briefArError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_brief">{{timeLabel}}</label>
                            <div class="col-sm-10">
                                {{{time}}}
                                {{{timeError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_duration">{{durationLabel}}</label>
                            <div class="col-sm-10">
                                {{{duration}}}
                                {{{durationError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label required"  for="course_form_price">{{priceLabel}}</label>
                            <div class="col-sm-10">
                                {{{price}}}
                                {{{priceError}}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>
                                <span class="control-label">{{isForInstructorLabel}}</span>
                                {{{isForInstructor}}}
                                {{{isForInstructorError}}}
                            </label>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row panel-border">
                    <h2 class="sub-title-form"> COURSE OUTLINES DATA</h2>
                    <div class="col-md-12">
                        <div class="form-group">
                            {{{outlines}}}
                            {{{outlinesError}}}
                            {{{addFiveMore}}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            {{{id}}}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            {{{buttons}}}
                        </div>
                    </div>
                </div>
                {{{closeTag}}}
            </div>
        </div><!-- panel -->
    </div>
</div>
<div role="tabpanel" class="tab-pane" id="courseEvaluation">...</div>
<div role="tabpanel" class="tab-pane" id="courseResources">...</div>
</div>
{{/content}}

{{$scripts}}
<script>
    $(document).ready(function () {
    updateOutlines("#course_form_addFiveMore", {{#isAdminUser}}true{{/isAdminUser}}{{^isAdminUser}}false{{/isAdminUser}})
    });
</script>
{{/scripts}}
{{/layout}}
