{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/courses/new"><button class="btn btn-small btn-success">{{#translate}}Create new Course{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Courses{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Name{{/translate}}</th>
                <th>{{#translate}}Name in Arabic{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courses}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td>{{name}}</td>
                <td>{{nameAr}}</td>
                <td>{{statusText}}</td>

                <td>
                    <a href="/courses/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    {{#evaluation}}
                    <a href="/courses/evaluation/edit/{{evaluation.course.id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit Course Evaluation{{/translate}}"><span class="glyphicon glyphicon-list-alt"></span></a>
                    {{/evaluation}}
                    {{^evaluation}}
                    <a href="/courses/evaluation/new/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Create Course Evaluation{{/translate}}"><span class="glyphicon glyphicon-list-alt"></span></a>
                    {{/evaluation}}
                    &nbsp;&nbsp;&nbsp;
                    <a href="/courses/resources/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Resources{{/translate}}"><span class="glyphicon glyphicon-folder-close"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/course-events/{{id}}" data-toggle="tooltip" data-placement="left" title="Course Events"><span class="glyphicon glyphicon-calendar"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    {{#status}}
                    {{#isAdminUser}}
                    <a href="/courses/delete/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isAdminUser}}
                    {{/status}}

                </td>
            </tr>
            {{/courses}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
