{{% BLOCKS }}
{{<layout}}
{{$content}}

<br><br>
<h4 class="h4">{{#translate}}Course You Are Assigned To{{/translate}} ..</h4>

<div class="panel panel-default">

    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Course name{{/translate}}</th>
                <th>{{#translate}}Start Date{{/translate}}</th>
                <th>{{#translate}}End Date{{/translate}}</th>
                <th>{{#translate}}Duration{{/translate}} ({{#translate}}Days{{/translate}})</th>
                <th>{{#translate}}Authorized Training Partner{{/translate}}</th>
                <th>{{#translate}}Rating{{/translate}}</th>
                
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courseEvents}}
            <tr>
                <td>
                    {{#locale_en}}
                    {{course.name}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{course.nameAr}}
                    {{/locale_ar}}
                </td>

                <td>
                    {{startDate}}
                </td>
                <td>
                    {{endDate}}
                </td>
                <td>
                    {{course.duration}} {{#translate}}Days{{/translate}}
                </td>
                <td>
                    {{#locale_en}}
                    {{atp.commercialName}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{atp.commercialNameAr}}
                    {{/locale_ar}}
                </td>
                <td>
                    {{course.evaluation.percentage}} %
                </td>
                <td>
                    <a href="/courses/more/{{course.id}}" data-toggle="tooltip" data-placement="left" title="More"><span class="glyphicon glyphicon-plus"></span></a>
                </td>
            </tr>



            {{/courseEvents}}
        </tbody>
    </table>
    {{/content}}
    {{/layout}}
