{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .page-container {
        margin-right: 0px;
        margin-left: 0px;
        margin-top: -131px;
    }
</style>
<div class="main-holder">
    <!-- image course
     ================================================== -->  
    <div class="image-course">
        <div class="container">
            <div class="row row-centered">
                <div class="col-xs-12 col-centered  text-center">

                    <h1 class="course-name">{{course.name}}<br>
                        {{course.brief}}</h1>
                    <div class="inner-cont">
                        <p>{{course.duration}} {{#translate}}Day{{/translate}}(s).</p>
                        {{^course.currentUserEnrolled}}
                        <button class="btn-course-enroll"><a href="/courses/calendar">Enroll this course</a></button>
                        {{/course.currentUserEnrolled}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- end image course
   ================================================== --> 
    <!--making sure that user can evaluate-->
    {{#canEvaluate}}
    {{#courseEventId}}
    <!--this rule is only for students-->
    <a class="btn btn-info" href="/courses/vote/{{courseEventId}}" >{{#translate}}Evaluate Course{{/translate}}</a>
    <br><br>
    {{/courseEventId}}
    {{/canEvaluate}}
    <hr class="featurette-divider">

    <!-- tabs 
   ================================================== --> 

    <div class="tabs">
        <div class="container">
            <ul class="nav nav-tabs responsive" id="myTab">
                <li class="active"><a data-target="#about" data-toggle="tab">{{#translate}}About This Course{{/translate}}</a></li>
                {{^courseEventId}}
                <li><a data-target="#courseEvents" data-toggle="tab">{{#translate}}Course Events{{/translate}}</a></li>
                {{/courseEventId}}
                <li><a data-target="#courseOutlines" data-toggle="tab">{{#translate}}Course Outlines{{/translate}}</a></li>
                <li><a data-target="#courseResources" data-toggle="tab">{{#translate}}Course Resources{{/translate}}</a></li>
                {{#courseEventId}}
                {{#courseEventCreator}}
                <li><a data-target="#courseEventVotes" data-toggle="tab">{{#translate}}Votes{{/translate}}</a></li>
                <li><a data-target="#courseEventUsers" data-toggle="tab">{{#translate}}Enrolled Users{{/translate}}</a></li>
                {{/courseEventCreator}}
                {{/courseEventId}}
            </ul>

            <div class="tab-content responsive">
                <div class="tab-pane active" id="about">

                            {{#course}}
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>{{#translate}}Name{{/translate}}</td><td>{{name}}</td>
                                    </tr><tr>
                                        <td>{{#translate}}Name in Arabic{{/translate}}</td><td>{{nameAr}}</td>
                                    </tr><tr>
                                        <td>{{#translate}}Time{{/translate}}</td>
                                        <td>
                                            {{time}}
                                        </td>
                                    </tr><tr>
                                        <td>{{#translate}}Duration{{/translate}}</td>
                                        <td>
                                            {{duration}} {{#translate}}Day(s){{/translate}}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            {{/course}}
                        <div class="col-sm-1 "></div>
                        <div class="col-sm-6 course-date">
                            <div class="date">
                                <h3>{{#translate}}Course Dates{{/translate}}</h3>
                                {{#course}}
                                {{#course.courseEvents.count}}
                                {{#courseEvents}}
                                <ul>
                                    {{^hideFromCalendar}}
                                    {{^alreadyEnded}}    
                                    <li>{{#translate}}Starts at{{/translate}} {{startDate}} - {{#translate}}ends at{{/translate}} {{endDate}}</li>
                                    {{/alreadyEnded}}
                                    {{/hideFromCalendar}}
                                    {{/courseEvents}} 
                                </tbody>
                            </table>
                            {{/course.courseEvents.count}}
                            {{^course.courseEvents.count}}
                            {{#translate}}Nothing Yet{{/translate}} !
                            {{/course.courseEvents.count}}
                            {{/course}}
                        </div>
                    </div>
                </div>
                {{^courseEventId}}
                <div class="tab-pane fade" id="courseEvents">
                    <div class="row">
                        <div class="panel panel-default">
                            {{#courseEventCreator}}
                            <a class="btn btn-info" href="/course-events/new/{{course.id}}" >{{#translate}}Create new course event{{/translate}}</a>
                            {{/courseEventCreator}}
                            <div class="panel-heading">
                                <h3>{{#translate}}Course Events{{/translate}}</h3>
                            </div>
                            <div class="panel-body">
                                {{#course}}
                                {{#course.courseEvents.count}}
                                <table class="table">
                                    <thead>
                                        {{#courseEvents.count}}
                                        <tr>
                                            <th>{{#translate}}Start Date{{/translate}}</th>
                                            <th>{{#translate}}End Date{{/translate}}</th>
                                            <th>{{#translate}}Instructor{{/translate}}</th>
                                            <th>{{#translate}}ATP Name{{/translate}}</th>
                                            <th>{{#translate}}ATP City{{/translate}}</th>
                                        </tr>
                                        {{/courseEvents.count}}
                                    </thead>
                                    <tbody>
                                        {{#courseEvents}}
                                        {{^hideFromCalendar}}
                                        {{^alreadyEnded}}
                                        <tr>
                                            <td>{{startDate}}</td>
                                            <td>{{endDate}}</td>
                                            <td>{{ai.firstName}} {{ai.lastName}}</td>
                                            <td>{{atp.commercialName}}</td>
                                            <td>{{atp.city}}</td>
                                        </tr>
                                        {{/alreadyEnded}}
                                        {{/hideFromCalendar}}
                                        {{/courseEvents}} 
                                    </tbody>
                                </table>
                                {{/course.courseEvents.count}}
                                {{^course.courseEvents.count}}
                                Nothing Yet !
                                {{/course.courseEvents.count}}
                                {{/course}}
                            </div>
                        </div>
                    </div>
                </div>
                {{/courseEventId}}
                <div class="tab-pane fade" id="courseOutlines">
                    <div class="row">
                        <div class="panel-body">

                            {{#course}}
                            <table class="table">
                                <thead>
                                    {{#outlines.count}}
                                    <tr>
                                        <th>{{#translate}}Title{{/translate}}</th>
                                        <th>{{#translate}}Title in Arabic{{/translate}}</th>
                                        <th>{{#translate}}Duration (minutes){{/translate}}</th>
                                    </tr>
                                    {{/outlines.count}}
                                </thead>
                                <tbody>
                                    {{#outlines}}
                                    {{#statusActive}}
                                    <tr>
                                        <td>{{title}}</td>
                                        <td>{{titleAr}}</td>
                                        <td>{{duration}}</td>
                                    </tr>
                                    {{/statusActive}}
                                    {{/outlines}} 
                                </tbody>
                            </table>
                            {{/course}}
                        </div>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane fade" id="courseResources">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>{{#translate}}Course Resources{{/translate}}</h3>
                        </div>
                        <div class="panel-body">

                            {{#course}}
                            <table class="table">
                                <tbody>
                                    {{#canDownloadResources}}
                                    {{#resources}}
                                    <tr>
                                        <td>
                                            {{#translate}}{{type}}{{/translate}}
                                        </td>
                                        <td>
                                            {{#files}}
                                            <a target="_blank" href="/courses/resources/download/{{id}}" >{{name}}</a> <br>
                                            {{/files}}
                                        </td>
                                    </tr>
                                    {{/resources}} 
                                    {{/canDownloadResources}}
                                </tbody>
                            </table>
                            {{/course}}
                        </div>
                    </div>
                </div>
                {{#courseEventId}}
                {{#courseEventCreator}}
                <div class="tab-pane fade" id="courseEventVotes">
                    <div class="row">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3>{{#translate}}Votes{{/translate}}</h3>
                            </div>
                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                        {{#votes.0}}
                                        <tr>
                                            <th>{{#translate}}Question{{/translate}}</th>
                                            <th>{{#translate}}Average Vote{{/translate}}</th>
                                        </tr>
                                        {{/votes.0}}
                                    </thead>
                                    <tbody>
                                        {{#votes}}
                                        <tr>
                                            <td>{{#locale_ar}}{{questionTitleAr}}{{/locale_ar}}{{#locale_en}}{{questionTitle}}{{/locale_en}}</td>
                                            <td>{{votesPercent}} %</td>
                                        </tr>
                                        {{/votes}} 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="courseEventUsers">
                    <div class="row">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3>{{#translate}}Enrolled Users{{/translate}}</h3>
                            </div>
                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                        {{#courseEventUsers.count}}
                                        <tr>
                                            <th>{{#translate}}First Name{{/translate}}</th>
                                            <th>{{#translate}}Last Name{{/translate}}</th>
                                            <th>{{#translate}}Username{{/translate}}</th>
                                            <th>{{#translate}}Email{{/translate}}</th>
                                        </tr>
                                        {{/courseEventUsers.count}}
                                    </thead>
                                    <tbody>
                                        {{#courseEventUsers}}
                                        <tr>
                                            <td>
                                                {{#locale_en}}
                                                {{user.firstName}}
                                                {{/locale_en}}
                                                {{#locale_ar}}
                                                {{user.firstNameAr}}
                                                {{/locale_ar}}        
                                            </td>
                                            <td>
                                                {{#locale_en}}
                                                {{user.lastName}}
                                                {{/locale_en}}
                                                {{#locale_ar}}
                                                {{user.lastNameAr}}
                                                {{/locale_ar}}        
                                            </td>
                                            <td>{{user.username}}</td>
                                            <td>{{user.email}}</td>
                                        </tr>
                                        {{/courseEventUsers}} 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                {{/courseEventCreator}}
                {{/courseEventId}}
            </div>
        </div>
    </div>

</div>
{{/content}}
{{$scripts}}
    <script type="text/javascript" src="/js/more.js"></script>
    {{/scripts}}
{{/layout}}
