{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/courses/calendar"><button class="btn btn-small btn-success"><span class="glyphicon glyphicon-arrow-left"></span></button></a>
<br><br>

<br><br>
<!--making sure that user can evaluate-->
{{#canEvaluate}}
{{#courseEventId}}
<!--this rule is only for students-->
<a class="btn btn-info" href="/courses/vote/{{courseEventId}}" >Evaluate Course</a>
<br><br>
{{/courseEventId}}
{{/canEvaluate}}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#courseDetails" data-toggle="tab" aria-controls="courseDetails" role="tab" data-toggle="tab">Course Details</a></li>
    <li role="presentation"><a href="#courseEvents" data-toggle="tab" aria-controls="courseEvents">Course Events</a></li>
    <li role="presentation"><a href="#courseOutlines" data-toggle="tab" aria-controls="courseOutlines">Course Outlines</a></li>
    <li role="presentation"><a href="#courseResources" data-toggle="tab" aria-controls="courseResources">Course Resources</a></li>

</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="courseDetails">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Course Details</h3>
            </div>
            <div class="panel-body">

                {{#course}}
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Name</td><td>{{name}}</td>
                        </tr><tr>
                            <td>Brief</td><td>{{brief}}</td>
                        </tr><tr>
                            <td>Time</td><td>{{time}}</td>
                        </tr><tr>
                            <td>Duration</td><td>{{duration}} Day(s)</td>
                        </tr>
                    </tbody>
                </table>
                {{/course}}
            </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="courseEvents">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Course Events</h3>
            </div>
            <div class="panel-body">

                {{#course}}
                <table class="table">
                    <thead>

                        {{#courseEvents.count}}
                        <tr>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Instructor</th>
                            <th>ATP Name</th>
                            <th>ATP City</th>
                        </tr>
                        {{/courseEvents.count}}
                    </thead>
                    <tbody>
                        {{#courseEvents}}

                        <tr>
                            <td>{{startDate}}</td>
                            <td>{{endDate}}</td>
                            <td>{{ai.firstName}} {{ai.lastName}}</td>
                            <td>{{atp.commercialName}}</td>
                            <td>{{atp.city}}</td>
                        </tr>
                        {{/courseEvents}} 
                    </tbody>
                </table>
                {{/course}}
            </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="courseOutlines">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Course Outlines</h3>
            </div>
            <div class="panel-body">

                {{#course}}
                <table class="table">
                    <thead>
                        {{#outlines.count}}
                        <tr>
                            <th>Title</th>
                            <th>Duration (minutes)</th>
                        </tr>
                        {{/outlines.count}}
                    </thead>
                    <tbody>
                        {{#outlines}}
                        {{#statusActive}}
                        <tr>
                            <td>{{title}}</td>
                            <td>{{duration}}</td>
                        </tr>
                        {{/statusActive}}
                        {{/outlines}} 
                    </tbody>
                </table>
                {{/course}}
            </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="courseResources">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Course Resources</h3>
            </div>
            <div class="panel-body">

                {{#course}}
                <table class="table">
                    <tbody>
                        {{#canDownloadResources}}
                        {{#resources}}
                        <tr>
                            <td>{{type}}</td>
                            <td>
                                {{#files}}
                                <a target="_blank" href="/resources/download/{{id}}" >{{name}}</a> <br>
                                {{/files}}
                            </td>
                        </tr>
                        {{/resources}} 
                        {{/canDownloadResources}}
                    </tbody>
                </table>
                {{/course}}
            </div>
        </div>
    </div>
</div>
{{/content}}
{{/layout}}
