{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}New Course{{/translate}}</h3>
    </div>
    <div class="panel-body">
{{{courseForm}}}
    </div><!-- body -->
</div><!-- panel -->

{{/content}}
{{$scripts}}
<script>
    $(document).ready(function () {
    updateOutlines("#course_form_addOneMore", {{#isAdminUser}}true{{/isAdminUser}}{{^isAdminUser}}false{{/isAdminUser}})
    });
</script>
{{/scripts}}
{{/layout}}
