{{% BLOCKS }}
{{<layout}}
{{$content}}

<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translation}}Exam Requests{{/translation}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translation}}Course name{{/translation}}</th>
                <th>{{#translation}}Authorized Testing Center{{/translation}}</th>
                <th>{{#translation}}Exam Date{{/translation}}</th>
                <th>{{#translation}}Students No.{{/translation}}</th>
                <th>{{#translation}}Admin Status{{/translation}}</th>
                <th>{{#translation}}TVTC Status{{/translation}}</th>
                <th colspan="2">{{#translation}}Actions{{/translation}}</th>
            </tr>
        </thead>
        <tbody>
            {{#requests}}
            <tr>
                <td>{{course.name}}</td>
                <td>{{atc.commercialName}}</td>
                <td>{{date}}</td>
                <td>{{studentsNo}}</td>
                {{#isAdminPending}}
                <td><span class="error">{{adminStatus}}</span></td>
                {{/isAdminPending}}
                {{^isAdminPending}}
                <td><span>{{adminStatus}}</span></td>
                {{/isAdminPending}}
                
                {{#isTvtcPending}}
                <td><span class="error">{{tvtcStatus}}</span></td>
                {{/isTvtcPending}}
                {{^isTvtcPending}}
                <td><span>{{tvtcStatus}}</span></td>
                {{/isTvtcPending}}
                <td>
                    {{#isAdminPending}}
                    <a href="/courses/exam/request/accept/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translation}}Accept{{/translation}}"><span class="glyphicon glyphicon-ok"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/courses/exam/request/decline/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translation}}Delete{{/translation}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isAdminPending}}
                </td>
            </tr>
            {{/requests}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
