{{% BLOCKS }}
{{<layout}}
{{$content}}

<style>
    li{
        margin-top: 10px;
    }
</style>
<h1>{{#translate}}CertigatePro General Resources{{/translate}}</h1>


<ul style="list-style-type:none">

    <li>
        <ul style="list-style-type:none">
            {{#translate}}Logos{{/translate}} :
            <li>
                <a href="/general-resources/download/Logo.zip" download>{{#translate}}Certified instructor logo{{/translate}}</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
    <li>
        <ul style="list-style-type:none">
            {{#translate}}Order Forms{{/translate}} :
            <li>
                <a href="/general-resources/download/courseOrderForm.zip" download>{{#translate}}Course order form{{/translate}}</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
    <li>
        <ul style="list-style-type:none">
            {{#translate}}Templates{{/translate}} :
            <li>
                <a href="/general-resources/download/Course roaster templates.zip" download>{{#translate}}Course roaster templates{{/translate}}</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
</ul>

{{/content}}
{{/layout}}