{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="page-container-wide HomeContainer">
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active"><img class="first-slide" src="images/firstslider.jpg" width="1364" height="552"  alt="First slide"/>

                <div class="container">
                    <div class="carousel-caption">
                        <h1 class="slidefont">Learn from the best.</h1>
                        <p>Stay tuned as we reveal more of our approach and how we will change the way you learn, forever.</p>
                        {{^loggedInUsername}}
                        <p><a class="btn btn-lg btn-primary" href="/register" role="button">Sign up today</a></p>
                        {{/loggedInUsername}}
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="second-slide" src="images/second.jpg" width="1364" height="552"  alt="second slide"/>
                <div class="container">
                    <div class="carousel-caption">
                        <h1 class="slidefont">Another example headline.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide" src="images/third.jpg" width="1364" height="552"  alt="third slide"/>
                <div class="container">
                    <div class="carousel-caption">
                        <h1 class="slidefont">One more for good measure.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="gray-bg">

        <div class="container marketing">

            <!-- Three columns of text below the carousel -->
            <div class="row">
                <div class="col-lg-3 center-content">
                    <img class="" src="images/trainerpartner.png" alt="Generic placeholder image" width="117" height="117">
                    <h4 class="text-upper">Training Partner</h4>
                    <p>Multiple people, such institution or an association, to hcollective goal and is linked to an external 
                        such institution association.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-3 -->
                <div class="col-lg-3 center-content">
                    <img class="" src="images/testcenter.png" alt="Generic placeholder image" width="117" height="117">
                    <h4 class="text-upper">Testing Center</h4>
                    <p>Multiple people, such institution or an association, to hcollective goal and is linked to an external 
                        such institution association.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-3 -->
                <div class="col-lg-3 center-content">
                    <img class="" src="images/instructor.png" alt="Generic placeholder image" width="117" height="117">
                    <h4 class="text-upper">Instructor</h4>
                    <p>Multiple people, such institution or an association, to hcollective goal and is linked to an external 
                        such institution association.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-3 -->
                <div class="col-lg-3 center-content">
                    <img class="" src="images/trainee.png" alt="Generic placeholder image" width="117" height="117">
                    <h4 class="text-upper">Trainee</h4>
                    <p>Multiple people, such institution or an association, to hcollective goal and is linked to an external 
                        such institution association.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-3 -->
            </div>

        </div>
    </div>
    <!-- /.row -->


    <!-- START THE FEATURETTES -->

    <div class="container marketing">
        <!--      <hr class="featurette-divider"> -->

        <!-- START THE course section -->
        <div class="course">
            <div class="container marketing">
                <div class="row">
                    <h1 class="main-title">Latest Courses</h1>
                    <div class="col-lg-3 ">
                        <div class="course-item">

                            <img src="images/img-01.jpg"  class="img-responsive" alt="264x171" />

                            <div class="desc">
                                <div class="course-bg ">
                                    <h4 class="course-title">The Art of photpgrapher</h4>
                                </div>
                                <div class="content-course">
                                    <p class="desc_content">simply dummy text of the printing and typesetting industrybeen the industry's standard</p>
                                    <a> Starting Soon</a>
                                </div>
                            </div>

                        </div>            
                    </div>

                    <div class="col-lg-3 ">
                        <div class="course-item">
                            <img src="images/img-02.jpg"  class="img-responsive" alt="264x171" />
                            <div class="desc">
                                <div class="course-bg ">
                                    <h4 class="course-title">Learn Illustration</h4>
                                </div>
                                <div class="content-course">
                                    <p class="desc_content">simply dummy text of the printing and typesetting industrybeen the industry's standard</p>
                                    <a> Starting Soon</a>
                                </div>
                            </div>

                        </div>            
                    </div>

                    <div class="col-lg-3 ">
                        <div class="course-item">

                            <img src="images/img-03.jpg"  class="img-responsive" alt="264x171" />

                            <div class="desc">
                                <div class="course-bg ">
                                    <h4 class="course-title">Easy English And Grammer</h4>
                                </div>
                                <div class="content-course">
                                    <p class="desc_content">simply dummy text of the printing and typesetting industrybeen the industry's standard</p>
                                    <a> Starting Soon</a>
                                </div>
                            </div>

                        </div>            
                    </div>

                    <div class="col-lg-3 ">
                        <div class="course-item">

                            <img src="images/img-04.jpg"  class="img-responsive" alt="264x171" />

                            <div class="desc">
                                <div class="course-bg ">
                                    <h4 class="course-title">programming language </h4>
                                </div>
                                <div class="content-course">
                                    <p class="desc_content">simply dummy text of the printing and typesetting industrybeen the industry's standard</p>
                                    <a> Starting Soon</a>
                                </div>
                            </div>

                        </div>            
                    </div>


                </div>
            </div>
        </div>
    </div>
    <!-- END THE course section -->

    <!-- Start THE Small carousal-->
    <div class="small-carousel">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="images/img-05.jpg" alt="...">
                    <div class="carousel-caption">
                        <h3 class="small-ca">{{#translate}}Become an Instructor{{/translate}}</h3>
                        <p>Tech the world Online, Share your knowledge</p>
                        <button type="Start Now" class="start-now btn btn-white">Start Now</button>
                    </div>
                </div>

                <div class="item ">
                    <img src="images/img-06.jpg" alt="...">
                    <div class="carousel-caption">
                        <h3 class="small-ca">{{#translate}}Become a Student{{/translate}}</h3>
                        <p>Tech the world Online, Share your knowledge</p>
                        <button type="Start Now" class="start-now btn btn-white">Start Now</button>
                    </div>
                </div>

                <div class="item ">
                    <img src="images/img-07.jpg" alt="...">
                    <div class="carousel-caption">
                        <h3 class="small-ca">{{#translate}}Become a Proctor{{/translate}}</h3>
                        <p>Tech the world Online, Share your knowledge</p>
                        <button type="Start Now" class="start-now btn btn-white">Start Now</button>
                    </div>
                </div>

            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div> <!-- Carousel -->



    </div>
    <!-- END THE Small carousal-->
    <hr class="featurette-divider">
    <div class="container marketing">





        <div class="row featurette">
            <div class="col-md-4 ">
                <h2 class="news-heading">GET The UpDate.</h2>
                <p class="lead">Get notified about new courses, 
                    events, community news and more.</p>
            </div>
            <div class="col-md-8 news">

                <form action="" method="post" role="form">
                    <div class="input-group">

                        <input class="form-control" type="text" id="" name="" placeholder="your@email.com">
                    </div>
                    <input type="submit" value="Subscribe" class="btn btn-large btn-primary news-btn" />
                </form>
            </div>
        </div>

        <hr class="featurette-divider">

    </div> 
</div>
<!-- /END THE FEATURETTES -->

{{/content}}
{{/layout}}