{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .cover_image{
        width: 250px;
        height: 200px;
    }
    .summary{
        margin-top: 3px;
    }
    .news_body{
        margin-top: 20px;
    }
</style>


{{#details}}
<div class="row">
    <div class="col-lg-3 main_pic">
        <div class="imageContainer">
            <img class="cover_image" src="/upload/pagePictures/{{picture.tmp_name}}"/>
        </div>
    </div>
    <div class=" col-lg-7 news_head">
        <blockquote>
            {{#locale_en}}
            <h3 class="title-blue title-top">{{#translate}}{{title}}{{/translate}}</h3>
            {{/locale_en}}
            {{#locale_ar}}
            <h3 class="title-blue title-top">{{#translate}}{{titleAr}}{{/translate}}</h3>
            {{/locale_ar}}

            <footer>
                <span>By: {{author}}</span><span class="pull-right">{{created}}</span>
            </footer>
        </blockquote>


        <div class="summary">
            {{#locale_en}}
            {{summary}}
            {{/locale_en}}
            {{#locale_ar}}
            {{summaryAr}}
            {{/locale_ar}}
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-lg-12 news_body">
        {{#locale_en}}
        {{{body}}}
        {{/locale_en}}
        {{#locale_ar}}
        {{{bodyAr}}}
        {{/locale_ar}}
    </div> 
</div>

<button type="button" class="btn btn-info"  onclick="getStfForm()">Send to friend</button>

<a href="/cms/press-release/pdf/{{id}}"><button type="button" class="btn btn-success download_pdf">Download</button></a>

{{/details}}


{{/content}}
{{/layout}}
<script>
    function getStfForm() {
        bootbox.dialog({
                message:'{{{form}}}'
            });
        document.getElementById('contact_us_form_name').removeAttribute('required');
        document.getElementById('contact_us_form_name').parentNode.style.display = 'none';
        document.getElementById('contact_us_form_subject').removeAttribute('required');
        document.getElementById('contact_us_form_subject').parentNode.style.display = 'none';
        document.getElementById('contact_us_form_message').removeAttribute('required');
        document.getElementById('contact_us_form_message').parentNode.style.display = 'none';
    }
</script>
