{{% BLOCKS }}
{{<layout}}
{{$content}}

<div class="panel panel-default">

    <div class="row">
    <h1 class="title-blue col-md-4">{{#translate}}Press Releases{{/translate}}</h1>
    {{#pressReleaseSubscriptionForm}}
        <div class="col-md-offset-10">
            {{{pressReleaseSubscriptionForm}}}
        </div>
    </div>
    <br>
    {{/pressReleaseSubscriptionForm}}
    </div>
    <hr>

    {{#pressReleases}}

    <div class="row">
        <div class="col-md-1">&nbsp;</div>
        <div class="media col-md-10">
            <a class="pull-left" href="#">
                <img width="100" class="media-object" src="{{picture.tmp_name}}">
            </a>
            <div class="media-body">
                {{#locale_en}}
                    <h4 class="media-heading title-blue title-top">{{title}}</h4>
                {{/locale_en}}
                {{#locale_ar}}
                    <h4 class="media-heading title-blue title-top">{{titleAr}}</h4>
                {{/locale_ar}}
                
                <p class="text-right">By {{author}}</p>
                
                {{#locale_en}}
                    <p>{{summary}}</p>
                {{/locale_en}}
                {{#locale_ar}}
                    <p>{{summaryAr}}</p>
                {{/locale_ar}}
                <ul class="list-inline list-unstyled">
                    <a href="/cms/press-release/details/{{id}}" title="More"><p class="text-right">Read more ...</p></a>
                </ul>
            </div>
            <hr>
        </div>
        <div class="col-md-1">&nbsp;</div>
    </div>


    {{/pressReleases}}
    <hr class="featurette-divider"> 
</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > Pages :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}

{{/layout}}
