<style>
    .cover_image{
        width: 250px;
        height: 200px;
    }
    .summary{
        margin-top: 3px;
    }
    .news_body{
        margin-top: 20px;
    }
</style>
<div class="row">
    <div class="col-lg-3 main_pic">
        <div class="imageContainer">
            <img class="cover_image" src="/var/www/html/public/upload/pagePictures/<?php echo $this->tmp_name ?>"/>
        </div>
    </div>
    <div class=" col-lg-7 news_head">
        <blockquote>
            <?php if ($this->language): ?>
                <h3><?php echo $this->title ?></h3>
            <?php else : ?>
                <h3><?php echo $this->titleAr ?></h3>
            <?php endif; ?>
            <footer>
                <span>By: <?php echo $this->author ?></span><br>
                <span class="pull-right"><?php echo $this->created ?></span>
            </footer>
        </blockquote>


        <div class="summary">            
            <?php if ($this->language): ?>
                <?php echo $this->summary ?>
            <?php else : ?>
                <?php echo $this->summaryAr ?>
            <?php endif; ?>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-lg-12 news_body">
        <?php if ($this->language): ?>
            <?php echo $this->body ?>
        <?php else : ?>
            <?php echo $this->bodyAr ?>
        <?php endif; ?>
    </div> 
</div>
