{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Edit Menu Item{{/translate}}</h3>
    </div>
    <div class="panel-body">
        {{{menuItemForm}}}
    </div>
</div>
{{/content}}
{{$scripts}}
<script type="text/javascript" src="/js/menuItem.js"></script>
<script type="text/javascript">
    $(function () {
        $('.menu_item_type:checked').change();
    });
</script>
{{/scripts}}

{{/layout}}
