{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Process Quote{{/translate}}</h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <tbody>
                <tr>
                    <td>{{#translate}}Course Name{{/translate}}</td><td>{{course.name}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Course Name in Arabic{{/translate}}</td><td>{{course.nameAr}}</td>
                </tr>
                {{#isAdminUser}}
                <tr>
                    <td>{{#translate}}User Name{{/translate}}</td><td>{{quote.user.firstName}} {{quote.user.lastName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}User Name in Arabic{{/translate}}</td><td>{{quote.user.firstNameAr}} {{quote.user.lastNameAr}}</td>
                </tr>
                {{/isAdminUser}}

                {{#quote.existingCourseEvent}}
                <tr>
                    <td>{{#translate}}Start Date{{/translate}}</td><td>{{quote.courseEvent.startDate}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}End Date{{/translate}}</td><td>{{quote.courseEvent.endDate}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Instructor{{/translate}}</td><td>{{quote.courseEvent.ai.firstName}} {{quote.courseEvent.ai.lastName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Instructor in Arabic{{/translate}}</td><td>{{quote.courseEvent.ai.firstNameAr}} {{quote.courseEvent.ai.lastNameAr}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}ATP Name{{/translate}}</td><td>{{quote.courseEvent.atp.commercialName}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}ATP Name in Arabic{{/translate}}</td><td>{{quote.courseEvent.atp.commercialNameAr}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}ATP City{{/translate}}</td><td>{{quote.courseEvent.atp.city}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}ATP City in Arabic{{/translate}}</td><td>{{quote.courseEvent.atp.cityAr}}</td>
                </tr>
                {{/quote.existingCourseEvent}}

                {{#quote.isPrivate}}
                <tr>
                    <td>{{#translate}}Venue{{/translate}}</td><td>{{quote.venue}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Preferred Date{{/translate}}</td><td>{{quote.preferredDate}}</td>
                </tr>
                {{/quote.isPrivate}}

                {{#quote.isPublic}}
                <tr>
                    <td>{{#translate}}Seats No{{/translate}}</td><td>{{quote.seatsNo}}</td>
                </tr>
                {{/quote.isPublic}}

                {{#quote.isPriceSet}}
                    {{#quote.isPrivate}}
                    <tr>
                        <td>{{#translate}}Price{{/translate}}</td><td>{{quote.price}}</td>
                    </tr>
                    {{/quote.isPrivate}}

                    {{#quote.isPublic}}
                    <tr>
                        <td>{{#translate}}Unit Price{{/translate}}</td><td>{{quote.unitPrice}}</td>
                    </tr>
                    {{/quote.isPublic}}
                <tr>
                    <td>{{#translate}}Discount{{/translate}}</td><td>{{quote.discount}}</td>
                </tr>
                <tr>
                    <td>{{#translate}}Total{{/translate}}</td><td>{{quote.total}}</td>
                </tr>
                {{/quote.isPriceSet}}

                {{#quote.isWireTransferSet}}
                <tr>
                    <td>{{#translate}}Current Payment{{/translate}}</td><td><a target="_blank" href="/quote/download/{{type}}/{{id}}" >{{#translate}}Wire Transfer{{/translate}}</a></td>
                </tr>
                {{/quote.isWireTransferSet}}
            </tbody>
        </table>
        {{{form}}}
    </div>
</div>
{{/content}}
{{/layout}}
