{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit Course</h3>
    </div>
    <div class="panel-body">
        {{{courseForm}}}
    </div>
</div>
{{/content}}

{{$scripts}}
<script>
    $(document).ready(function () {
        updateOutlines("#course_form_addMore", {{#isAdminUser}}true{{/isAdminUser}}{{^isAdminUser}}false{{/isAdminUser}})
    });
</script>
{{/scripts}}
{{/layout}}
