{{% BLOCKS }}
{{<layout}}

{{$content}}
<style>
    .deleteQuestion{
        margin-top: -28px;
        float: right;
        margin-right: -28px;
    } 
</style>
<ul>    
    {{#validationError}}
    <li class="error">{{.}}</li>
    {{/validationError}}
</ul>
<form id="questions" class="form-horizontal" method="POST" action="">
    <fieldset>

        <!-- Form Name -->
        <legend>Evaluation Template</legend>
        {{#oldQuestions}}
        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label>  
            <div class=" col-md-4">
                <input name="newQuestion[]" type="text" placeholder="Add Your Question Here" class="form-control questionInputs input-md" required=""value="{{.}}">
                <a href="#" class="deleteQuestion" >X</a>
            </div>
        </div>
        {{/oldQuestions}}
        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label>  
            <div class="col-md-4">
                <input name="newQuestion[]" type="text" placeholder="Add Your Question Here" class="form-control questionInputs input-md" required="">
            </div>
        </div>
        <span id="endOfText"></span>
        <!-- button -->
        <div class=" row form-group">
            <div class="col-md-4">
                <button id="singlebutton" name="submit" class="btn btn-success">Submit Evaluation Template</button>
            </div>
        </div>

    </fieldset>
</form>

<button type="button" id="addmore" class=" btn btn-primary">Add More</button>


<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>
$(document).ready(function () {
    window.index = 1;


    $('#addmore').click(function () {
        getMeNewInput();
    });

    function getMeNewInput() {
        window.template = '<div class="form-group"> <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label> <div class="col-md-4"> <input name="newQuestion[' + window.index + ']" type="text" placeholder="Add Your Question Here" class="form-control input-md" required=""> </div> </div>';
        $('#endOfText').before(window.template);
        window.index++;

    }

    /**
     * This action is meant to delete 
     */
    $('.deleteQuestion').click(function () {
        // delete template 
        $(this).parent().parent().remove();
    });

});

</script>


{{/content}}

{{/layout}}