{{% BLOCKS }}
{{<layout}}

{{$content}}

<ul>    
    {{#validationError}}
    <li>{{.}}</li>
    {{/validationError}}
</ul>
<form id="questions" class="form-horizontal" method="POST" action="">
    <fieldset>

        <!-- Form Name -->
        <legend>Evaluation Template</legend>

        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="questionTitle[0]">Question Title</label>  
            <div class="col-md-4">
                <input id="questionTitle_0" name="questionTitle[0]" type="text" placeholder="Add Your Question Here" class="form-control sameLine input-md" required="">
            </div>
        </div>
        <span id="endOfText"></span>
        <!-- button -->
        <div class=" row form-group">
            <div class="col-md-4">
                <button id="singlebutton" name="submit" class="btn btn-success">Submit Evaluation Template</button>
            </div>
        </div>

    </fieldset>
</form>

<button type="button" id="addmore" class=" btn btn-primary">Add More</button>


<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>
$(document).ready(function () {
    window.index = 1;


    $('#addmore').click(function () {
        getMeNewInput();
    });

    function getMeNewInput() {
        window.template = '<div class="form-group"> <label class="col-md-4 control-label" for="questionTitle[]">Question Title</label> <div class="col-md-4"> <input id="questionTitle_" name="questionTitle[' + window.index + ']" type="text" placeholder="Add Your Question Here" class="form-control input-md" required=""> </div> </div>';
        $('#endOfText').before(window.template);
        window.index++;

    }


});

</script>


{{/content}}

{{/layout}}