{{% BLOCKS }}
{{<layout}}
{{$content}}
<br />
<a href="/organizations/new/{{atcTypeId}}"><button class="btn btn-small btn-success create-new">{{#translate}}Create new ATC{{/translate}}</button></a>
<br/>
<div class="panel panel-default atcs-list">
    <div class="panel-heading">{{#translate}}ATCs{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Commercial Name{{/translate}}</th>
                <th>{{#translate}}City{{/translate}}</th>
                <th>{{#translate}}Phone{{/translate}}</th>
                <th>{{#translate}}WebSite{{/translate}}</th>
                <th>{{#translate}}ATC License Expiration{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#atcs}}
            <tr>
                <td>
                    {{#locale_en}}
                    {{commercialName}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{commercialName}}
                    {{/locale_ar}}        
                </td>
                <td>
                    {{#locale_en}}
                    {{city}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{city}}
                    {{/locale_ar}}        
                </td>
                <td>{{phone1}}</td>
                <td>{{website}}</td>
                <td>{{atcLicenseExpiration}}</td>
                <td>
                    <a href="/organizations/more/{{id}}" title="More">{{#translate}}More{{/translate}}</a>     
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#orgUser}}
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#isAdmin}}
                    {{#status}}
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}" href="/organizations/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{/isAdmin}}
                    {{/orgUser}}

                    {{^orgUser}}
                    {{#isAdmin}}

                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#status}}
                    <a onclick="deleteOrganization({{id}}) "data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{/isAdmin}}
                    {{/orgUser}}

                </td>
            </tr>
            {{/atcs}}
        </tbody>
    </table>
</div>

{{/content}}

{{/layout}}
<script>
            function deleteOrganization(id) {

            message = "{{#translate}}Are you sure you want to delete this organization{{/translate}} ..?!";
                    url = '/organizations/delete/' + id;
                    bootbox.confirm(message, function (result) {
                    if (result) {
                    window.location.assign(url);
                    }
                    });
            }
</script>