{{% BLOCKS }}
{{<layout}}
{{$content}}
<br />
<a href="/organizations/new/{{atpTypeId}}"><button class="btn btn-small btn-success create-new">{{#translate}}Create new ATP{{/translate}}</button></a>
<br/>
<div class="panel panel-default atps-list">
    <div class="panel-heading">{{#translate}}ATPs{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Commercial Name{{/translate}}</th>
                <th>{{#translate}}Address{{/translate}}</th>
                <th>{{#translate}}Phone{{/translate}}</th>
                <th>{{#translate}}Email{{/translate}}</th>
                <th>{{#translate}}WebSite{{/translate}}</th>
                <th>{{#translate}}City{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#atps}}
            <tr>
                <td>{{commercialName}}</td>
                <td>{{addressLine1}}</td>
                <td>{{phone1}}</td>
                <td>{{email}}</td>
                <td>{{website}}</td>
                <td>{{city}}</td>
                <td>
                    {{#orgUser}}
                    <a href="/organizations/more/{{id}}" title="More">{{#translate}}More{{/translate}}</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#isAdmin}}
                    {{#status}}
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}" href="/organizations/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{/isAdmin}}
                    {{/orgUser}}
                    {{^orgUser}}
                    {{#isAdmin}}
                    <a href="/organizations/more/{{id}}" title="More">{{#translate}}More{{/translate}}</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#status}}
                    <a onclick="deleteOrganization({{id}}) "data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{/isAdmin}}
                    {{/orgUser}}
                </td>
            </tr>
            {{/atps}}
        </tbody>
    </table>
</div>

{{/content}}

{{/layout}}
<script>
    function deleteOrganization(id) {

        message = "{{#translate}}Are you sure you want to delete this organization{{/translate}} ..?!";
        url = '/organizations/delete/' + id;
        bootbox.confirm(message, function (result) {
            if (result) {
                window.location.assign(url);
            }
        });
    }
</script>