{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .page-container {
        margin-right: 5%;
        margin-left: 5%;
    }
</style>
<div class="main-holder">
    <div class="container">
        <div class="page-container">
            <div class="row">
                <div class="col-md-12 col-md-offset-0">
                    <div class="panel panel-default ">
                        <div class="panel-heading">
                            <h3>{{#translate}}New Organization{{/translate}}</h3>
                        </div>
                        <div class="panel-body main-form  ">
                            {{{openTag}}}
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}ACCOUNT DATA{{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_commercialName">{{#translate}}{{commercialNameLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{type}}}
                                            {{{typeError}}}
                                            {{{commercialName}}}
                                            {{{commercialNameError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_commercialNameAr">{{#translate}}{{commercialNameArLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{commercialNameAr}}}
                                            {{{commercialNameArError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_ownerName">{{#translate}}{{ownerNameLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{ownerName}}}
                                            {{{ownerNameError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_ownerNameAr">{{#translate}}{{ownerNameArLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{ownerNameAr}}}
                                            {{{ownerNameArError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_ownerNationalId">{{#translate}}{{ownerNationalIdLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{ownerNationalId}}}
                                            {{{ownerNationalIdError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}CERTIFICATE OF REGISTRATION (CR) {{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_CRNo">{{#translate}}{{CRNoLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{CRNo}}}
                                            {{{CRNoError}}}
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_CRAttachment">{{#translate}}{{CRAttachmentLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{CRAttachment}}}
                                            {{{CRAttachmentError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_CRExpirationHj">{{#translate}}{{CRExpirationHjLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{CRExpirationHj}}}
                                            {{{CRExpirationHjError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_CRExpiration">{{#translate}}{{CRExpirationLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{CRExpiration}}}
                                            {{{CRExpirationError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}LOCATION{{/translate}}</h2>
                                <div class="col-md-12">
                                    <div class="gllpMap">Google Maps</div>
                                    <div class="form-group">
                                        {{{mapSearch}}}
                                        {{{latitude}}}
                                        {{{latitudeError}}}
                                        {{{longitude}}}
                                        {{{longitudeError}}}
                                        {{{mapZoom}}}
                                        {{{mapSearchButton}}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_city">{{#translate}}{{cityLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{city}}}
                                            {{{cityError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_cityAr">{{#translate}}{{cityArLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{cityAr}}}
                                            {{{cityArError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_governorate">{{#translate}}{{governorateLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{governorate}}}
                                            {{{governorateError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_region">{{#translate}}{{regionLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{region}}}
                                            {{{regionError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_addressLine1">{{#translate}}{{addressLine1Label}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{addressLine1}}}
                                            {{{addressLine1Error}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_addressLine1Ar">{{#translate}}{{addressLine1ArLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{addressLine1Ar}}}
                                            {{{addressLine1ArError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label "  for="org_form_addressLine2">{{#translate}}{{addressLine2Label}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{addressLine2}}}
                                            {{{addressLine2Error}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label "  for="org_form_addressLine2Ar">{{#translate}}{{addressLine2ArLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{addressLine2Ar}}}
                                            {{{addressLine2ArError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required "  for="org_form_zipCode">{{#translate}}{{zipCodeLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{zipCode}}}
                                            {{{zipCodeError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}COMMUNICATION {{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_phone1">{{#translate}}{{phone1Label}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{phone1}}}
                                            {{{phone1Error}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label"  for="org_form_phone2">{{#translate}}{{phone2Label}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{phone2}}}
                                            {{{phone2Error}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label"  for="org_form_phone3">{{#translate}}{{phone3Label}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{phone3}}}
                                            {{{phone3Error}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label"  for="org_form_fax">{{#translate}}{{faxLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{fax}}}
                                            {{{faxError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required "  for="org_form_website">{{#translate}}{{websiteLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{website}}}
                                            {{{websiteError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required "  for="org_form_email">{{#translate}}{{emailLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{email}}}
                                            {{{emailError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{#atcLicenseNo}}
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}ATC License DATA {{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atcLicenseNo">{{#translate}}{{atcLicenseNoLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atcLicenseNo}}}
                                            {{{atcLicenseNoError}}}
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atcLicenseAttachment">{{#translate}}{{atcLicenseAttachmentLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atcLicenseAttachment}}}
                                            {{{atcLicenseAttachmentError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atcWireTransferAttachment">{{#translate}}{{atcWireTransferAttachmentLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atcWireTransferAttachment}}}
                                            {{{atcWireTransferAttachmentError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atcLicenseExpirationHj">{{#translate}}{{atcLicenseExpirationHjLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atcLicenseExpirationHj}}}
                                            {{{atcLicenseExpirationHjError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atcLicenseExpiration">{{#translate}}{{atcLicenseExpirationLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atcLicenseExpiration}}}
                                            {{{atcLicenseExpirationError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{/atcLicenseNo}}

                            {{#labsNo}}
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}ATC ASSETS {{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_labsNo">{{#translate}}{{labsNoLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{labsNo}}}
                                            {{{labsNoError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_pcsNo_lab">{{#translate}}{{pcsNo_labLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{pcsNo_lab}}}
                                            {{{pcsNo_labError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_internetSpeed_lab">{{#translate}}{{internetSpeed_labLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{internetSpeed_lab}}}
                                            {{{internetSpeed_labError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_operatingSystem">{{#translate}}{{operatingSystemLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{operatingSystem}}}
                                            {{{operatingSystemError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_operatingSystemLang">{{#translate}}{{operatingSystemLangLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{operatingSystemLang}}}
                                            {{{operatingSystemLangError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_officeLang">{{#translate}}{{officeLangLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{officeLang}}}
                                            {{{officeLangError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_officeVersion">{{#translate}}{{officeVersionLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{officeVersion}}}
                                            {{{officeVersionError}}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{/labsNo}}

                            {{#atpLicenseNo}}
                            <div class="row panel-border">
                                <h2 class="sub-title-form">{{#translate}}ATP License DATA {{/translate}}</h2>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atpLicenseNo">{{#translate}}{{atpLicenseNoLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atpLicenseNo}}}
                                            {{{atpLicenseNoError}}}
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atpLicenseAttachment">{{#translate}}{{atpLicenseAttachmentLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atpLicenseAttachment}}}
                                            {{{atpLicenseAttachmentError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atpWireTransferAttachment">{{#translate}}{{atpWireTransferAttachmentLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atpWireTransferAttachment}}}
                                            {{{atpWireTransferAttachmentError}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atpLicenseExpirationHj">{{#translate}}{{atpLicenseExpirationHjLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atpLicenseExpirationHj}}}
                                            {{{atpLicenseExpirationHjerror}}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label required"  for="org_form_atpLicenseExpiration">{{#translate}}{{atpLicenseExpirationLabel}}{{/translate}}</label>
                                        <div class="col-sm-9">
                                            {{{atpLicenseExpiration}}}
                                            {{{atpLicenseExpirationError}}}
                                        </div>
                                    </div>
                                </div>                             
                                {{/atpLicenseNo}}

                                {{#classesNo}}
                                <div class="row panel-border">
                                    <h2 class="sub-title-form">{{#translate}}ATP ASSETS {{/translate}}</h2>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label required"  for="org_form_classesNo">{{#translate}}{{classesNoLabel}}{{/translate}}</label>
                                            <div class="col-sm-9">
                                                {{{classesNo}}}
                                                {{{classesNoError}}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label required"  for="org_form_pcsNo_class">{{#translate}}{{pcsNo_classLabel}}{{/translate}}</label>
                                            <div class="col-sm-9">
                                                {{{pcsNo_class}}}
                                                {{{pcsNo_classError}}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {{/classesNo}}

                                <div class="row panel-border">
                                    <h2 class="sub-title-form">{{#translate}}ADMINISTRATORS {{/translate}}</h2>

                                    {{#atcLicenseNo}}
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label"  for="org_form_testCenterAdmin_id">{{#translate}}{{testCenterAdmin_idLabel}}{{/translate}}</label>
                                            <div class="col-sm-9">
                                                {{{testCenterAdmin_id}}}
                                                {{{testCenterAdmin_idError}}}
                                            </div>
                                        </div>
                                    </div>
                                    {{/atcLicenseNo}}

                                    {{#atpLicenseNo}}
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label "  for="org_form_trainingManager_id">{{#translate}}{{trainingManager_idLabel}}{{/translate}}</label>
                                            <div class="col-sm-9">
                                                {{{trainingManager_id}}}
                                                {{{trainingManager_idError}}}
                                            </div>
                                        </div>
                                    </div>
                                    {{/atpLicenseNo}}

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label required"  for="org_form_focalContactPerson_id">{{#translate}}{{focalContactPerson_idLabel}}{{/translate}}</label>
                                            <div class="col-sm-9">
                                                {{{focalContactPerson_id}}}
                                                {{{focalContactPerson_idError}}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {{#atcPrivacyStatement}}
                                <div class="col-md-12">
                                    <label  class="col-sm-3 control-label required atcSet"  for="org_form_atcPrivacyStatement">{{#translate}}{{atcPrivacyStatementLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{atcPrivacyStatement}}}
                                        {{{atcPrivacyStatementError}}}
                                    </div>
                                </div>
                                {{/atcPrivacyStatement}}

                                {{#atpPrivacyStatement}}
                                <div class="col-md-12">
                                    <label  class="col-sm-3 control-label required atpSet"  for="org_form_atpPrivacyStatement">{{#translate}}{{atpPrivacyStatementLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{atpPrivacyStatement}}}
                                        {{{atpPrivacyStatementError}}}
                                    </div>
                                </div>
                                {{/atpPrivacyStatement}}

                                {{#status}}
                                <div class="col-md-12">
                                    <label  class="col-sm-3 control-label atpSet"  for="org_form_status">{{#translate}}{{statusLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{status}}}
                                        {{{statusError}}}
                                    </div>
                                </div>
                                {{/status}}
                                {{{id}}}
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-sm-6">
                                        {{{save}}}
                                        &nbsp;&nbsp;
                                        {{{saveState}}}
                                        &nbsp;&nbsp;
                                        {{{reset}}}
                                    </div>
                                </div>
                            </div>
                            {{{closeTag}}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Modals-->
    <div class="modal fade atcSet" id="AtcModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">{{#translate}}ATC Privacy Statement{{/translate}}</h4>
                </div>
                <div class="modal-body">
                    {{#translate}}ATC Privacy Statement{{/translate}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Close{{/translate}}</button>
                    <button type="button" class="btn btn-primary" id="atcModalLinkAgree" data-dismiss="modal" aria-label="Close">{{#translate}}I agree{{/translate}}</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade atpSet" id="AtpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel" >{{#translate}}ATP Privacy Statement{{/translate}}</h4>
                </div>
                <div class="modal-body">
                    {{#translate}}ATP Privacy Statement{{/translate}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Close{{/translate}}</button>
                    <button type="button" class="btn btn-primary" id="atpModalLinkAgree" data-dismiss="modal" aria-label="Close">{{#translate}}I agree{{/translate}}</button>
                </div>
            </div>
        </div>
    </div>
    {{/content}}
    {{$scripts}}
    <script src="https://maps.googleapis.com/maps/api/js?key={{googleMapsApiKey}}"></script>
    {{/scripts}}
    {{/layout}}
