{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/organizations/type"><button class="btn btn-small btn-success">{{#translate}}Create new Organization{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Organizations{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Commercial name{{/translate}}</th>
                <th>{{#translate}}Owner name{{/translate}}</th>
                <th>{{#translate}}Type{{/translate}}</th>
                <th>{{#translate}}E-mail{{/translate}}</th>
                <th>{{#translate}}City{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#organizations}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td>
                    <a href="{{website}}" target="_blank">
                        {{#locale_en}}
                        {{commercialName}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{commercialNameAr}}
                        {{/locale_ar}}        
                    </a>
                </td>
                <td>
                    {{#locale_en}}
                    {{ownerName}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{ownerNameAr}}
                    {{/locale_ar}}        
                </td>
                <td>{{#translate}}{{typeText}}{{/translate}}</td>
                <td><a href="mailto:{{email}}" target="_blank">{{email}}</a></td>
                <td>
                    {{#locale_en}}
                    {{city}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{city}}
                    {{/locale_ar}}
                </td>
                <td>{{#translate}}{{statusText}}{{/translate}}</td>
                <td>
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/organizations/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a onclick="deleteOrganization({{id}}) "data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/organizations}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
<script>
            function deleteOrganization(id) {

            message = "{{#translate}}Are you sure you want to delete this organization{{/translate}} ..?!";
                    url = '/organizations/delete/' + id;
                    bootbox.confirm(message, function (result) {
                    if (result) {
                    window.location.assign(url);
                    }
                    });
            }
</script>