{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}New User{{/translate}}</h3>
    </div>
    <div class="panel-body">
        {{{userForm}}}
    </div>
</div>
{{/content}}


{{$scripts}}
{{> ../modules/users/index/userCRUD.js }}
<script>
    $(document).ready(function () {
        {{#statements}}
                generateStatementCheckboxContent('user_form_' + '{{type}}', '{{#translate}}{{title}}{{/translate}}', '{{#translate}}{{{sentence}}}{{/translate}}', '{{#translate}}{{{content}}}{{/translate}}', '{{#translate}}{{role}}{{/translate}}');
        {{/statements}}
        displayStatementCheckbox('input[name="roles[]"]');
        
        
            {{#success}}
            
            if({{success}}){
                alert('Saved Successfully');
            }
            
            {{/success}}
            
    });
</script>
{{/scripts}}
{{/layout}}
