{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit User</h3>
                 <img src="{{photo}}" data-toggle="tooltip" data-placement="left"  class="user-photos" style="height: 70px !important;width: 70px !important;">
    </div>
    <div class="panel-body">
        {{{userForm}}}
    </div>
</div>
{{/content}}

{{/layout}}
