{{% BLOCKS }}
{{<layout}}
{{$content}}
<br />
<a href="/users/new"><button class="btn btn-small btn-success">Create new User</button></a>
<br><br>
<div class="panel panel-default users-list">
    <div class="panel-heading">Users</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Photo</th>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>User Name</th>
                <th>Email</th>
                <th>Identification Type</th>
                <th>Identification Number</th>
                <th>Country</th>
                <th>Language</th>
                <th>Status</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#userList}}
            <tr>
                <th scope="row"><img src="{{photo}}" data-toggle="tooltip" data-placement="left" title="{{name}}" class="user-photos" style="height: 70px !important;width: 70px !important;"></th>
                <td>{{id}}</td>
                <td>{{firstName}}</td>
                <td>{{lastName}}</td>
                <td>{{username}}</td>
                <td>{{email}}</td>
                <td>{{identificationType}}</td>
                <td>{{identificationNumber}}</td>
                <td>{{countryText}}</td>
                <td>{{languageText}}</td>
                <td>{{statusText}}</td>
                <td>

                    <a data-toggle="tooltip" data-placement="left" title="Edit" href="/users/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a data-toggle="tooltip" data-placement="left" title="Delete" href="/users/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/userList}}
        </tbody>
    </table>
</div>
<br>
{{/content}}

{{/layout}}
