{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>New User</h3>
    </div>
    <div class="panel-body">
        {{{userForm}}}
    </div>
</div>
{{/content}}

{{$scripts}}
<script>
    $(document).ready(function () {
        {{#statements}}
                generateStatementCheckboxContent('user_form_' + '{{type}}', '{{title}}', '{{{sentence}}}', '{{{content}}}', '{{role}}');
        {{/statements}}
        displayStatementCheckbox('#user_form_roles');
    });
</script>
{{/scripts}}
{{/layout}}
