{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/system/settings/new"class="btn btn-small btn-success create-new">Create new Setting</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Settings</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Value</th>
                <th>Created</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#settings}}
            <tr>
                <td>{{name}}</td>
                <td>{{value}}</td>
                <td>{{created}}</td>
                <td>
                    <a href="/system/settings/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/system/settings/delete/{{id}}" class="delete_row" data-toggle="tooltip" data-placement="left" title="Delete"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
            {{/settings}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
