{{% BLOCKS }}
{{<layout}}
{{$content}}

<style>
    li{
        margin-top: 10px;
    }
</style>
<h1>CertigatePro General Resources</h1>


<ul style="list-style-type:none">

    <li>
        <ul style="list-style-type:none">
            Logos :
            <li>
                <a href="/general-resources/download/Logo.zip" download>Certified instructor logo</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
    <li>
        <ul style="list-style-type:none">
            Order Forms :
            <li>
                <a href="/general-resources/download/courseOrderForm.zip" download>Course order form</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
    <li>
        <ul style="list-style-type:none">
            Templates :
            <li>
                <a href="/general-resources/download/Course roaster templates.zip" download>Course roaster templates</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-download-alt"></span> 
            </li>
        </ul>
    </li>
</ul>

{{/content}}
{{/layout}}