{{% BLOCKS }}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/concat/app.css" rel="stylesheet" type="text/css"/>
        <title>{{$title}}Certigate Pro{{/title}}</title>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}
    </head>

    <body>

        {{<primary_menu}}
        {{/primary_menu}}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Certigate Pro</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/"></a></li>
                        <li><a href="/users">Users</a></li>
                        <li><a href="/cms/page">Pages</a></li>
                        <li><a href="/cms/menu">Menu</a></li>
                        <li><a href="/cms/menuitem">Menu Item</a></li>
                        <li><a href="/roles">Roles</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Reports</a></li>
                        <li><a href="#">Analytics</a></li>
                        <li><a href="#">Export</a></li>
                        <li><a href="/sign/out">Log out &nbsp;&nbsp;<i class="glyphicon glyphicon-log-out fa-fw " ></i><span class="fa arrow"></span></a></li>
                        
                    </ul>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <div id="page-wrapper">

                        <!-- /.row -->
                        <div class="row">
                            <div class="col-lg-12">
                                {{$content}}{{/content}}  
                            </div>
                            <!-- /.col-lg-12 -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /#page-wrapper -->
                </div>
            </div>
        </div>

        <script src="/concat/app.js" type="text/javascript"></script>
        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}
    </body>
</html>
