{{% BLOCKS }}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/concat/app.css" rel="stylesheet" type="text/css"/>
        <title>{{$title}}Certigate Pro{{/title}}</title>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Certigate Pro</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <h4>Primary Menu</h4>
                    {{<primary_menu}}
                    {{/primary_menu}}
                    
                    {{#adminMenu}}
                        <h4>Admin Menu</h4>
                        {{{adminMenu}}}
                    {{/adminMenu}}
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <div id="page-wrapper">

                        <!-- /.row -->
                        <div class="row">
                            <div class="col-lg-12">
                                {{$content}}{{/content}}  
                            </div>
                            <!-- /.col-lg-12 -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /#page-wrapper -->
                </div>
            </div>
        </div>

        <script src="/concat/app.js" type="text/javascript"></script>
        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}
    </body>
</html>
