{{% BLOCKS }}
<!doctype html>
<html>

    <head>
        <meta charset="UTF-8">
        <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}

    </head>

    <body>

        <div id="page-wrapper">

            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    {{$content}}{{/content}}  
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

        <script src="js/jquery.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}
    </body>

</html>
