{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/cms/page/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Page{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Pages{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Title{{/translate}}</th>
                <th>{{#translate}}Path{{/translate}}</th>
                <th>{{#translate}}Type{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th>{{#translate}}Created{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#pages}}
            <tr class="{{^status}}container-inactive{{/status}}" >
                <td>{{title}}</td>         
                <td>{{path}}</td>
                <td>{{type}}</td>
                <td>{{statusText}}</td>
                <td>{{created}}</td>
                <td>
                    <a href="/cms/page/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a  onclick="tooglePage(false,{{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Deactivate{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{^status}}
                    &nbsp;&nbsp;&nbsp;
                    <a onclick="tooglePage(true,{{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Activate{{/translate}}"><span class="glyphicon glyphicon-arrow-up"></span></a>
                    {{/status}}
                    {{#isAdminUser}}
                    &nbsp;&nbsp;&nbsp;
                    <a href="/cms/page/history/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}History{{/translate}}"><span class="glyphicon glyphicon-time"></span></a>
                    {{/isAdminUser}}
                </td>
            </tr>
            {{/pages}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
<script>
    function tooglePage(status, id){
            message = '';
            url = '';
            if (status){
                message = "{{#translate}}Are you sure you want to activate this page{{/translate}} ..?!";
                url = '/cms/page/activate/' + id;
            } else{
                message = "{{#translate}}Are you sure you want to deactivate this page{{/translate}} ..?!";
                url = '/cms/page/deactivate/' + id;
            }
            bootbox.confirm(message, function(result) {
                if (result){
                    window.location.assign(url);
                }
            });
    }    
</script>