{{% BLOCKS }}
{{<layout}}
{{$content}}
<br />
<a href="/organizations/new/{{atcTypeId}}"><button class="btn btn-small btn-success create-new">{{#translate}}Create new ATC{{/translate}}</button></a>
<br/>
<div class="panel panel-default atcs-list">
    <div class="panel-heading">{{#translate}}ATCs{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Commercial Name{{/translate}}</th>
                <th>{{#translate}}Commercial Name in Arabic{{/translate}}</th>
                <th>{{#translate}}City{{/translate}}</th>
                <th>{{#translate}}City in Arabic{{/translate}}</th>
                <th>{{#translate}}Phone{{/translate}}</th>
                <th>{{#translate}}WebSite{{/translate}}</th>
                <th>{{#translate}}ATC License Expiration{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#atcs}}
            <tr>
                <td>{{commercialName}}</td>
                <td>{{commercialNameAr}}</td>
                <td>{{city}}</td>
                <td>{{cityAr}}</td>
                <td>{{phone1}}</td>
                <td>{{website}}</td>
                <td>{{atcLicenseExpiration}}</td>
                <td>
                    <a href="/organizations/more/{{id}}">{{#translate}}More{{/translate}}</a>     
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#orgUser}}
                        <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {{#status}}
                        <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}" href="/organizations/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                        {{/status}}
                    {{/orgUser}}
                    {{^orgUser}}
                    {{#isAdmin}}
                        <a data-toggle="tooltip" data-placement="left" title="Manage Users" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="View"><span class="glyphicon glyphicon-eye-open"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a data-toggle="tooltip" data-placement="left" title="Edit" href="/organizations/edit/{{id}}"><span class="glyphicon glyphicon-edit"></span></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {{#status}}
                        <a data-toggle="tooltip" data-placement="left" title="Delete" href="/organizations/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                        {{/status}}
                    {{/isAdmin}}
                    {{/orgUser}}

                </td>
            </tr>
            {{/atcs}}
        </tbody>
    </table>
</div>

{{/content}}

{{/layout}}
