{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/organizations/type"><button class="btn btn-small btn-success">{{#translate}}Create new Organization{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Organizations{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Commercial name{{/translate}}</th>
                <th>{{#translate}}Owner name{{/translate}}</th>
                <th>{{#translate}}Type{{/translate}}</th>
                <th>{{#translate}}E-mail{{/translate}}</th>
                <th>{{#translate}}City{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#organizations}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td><a href="{{website}}" target="_blank">{{commercialName}}</a></td>
                <td>{{ownerName}}</td>
                <td>{{typeText}}</td>
                <td><a href="mailto:{{email}}" target="_blank">{{email}}</a></td>
                <td>{{city}}</td>
                <td>{{statusText}}</td>
                <td>
                    <a data-toggle="tooltip" data-placement="left" title="{{#translate}}Manage Users{{/translate}}" href="/organization-users/{{id}}"><span class="glyphicon glyphicon-user"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/organizations/pending/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/organizations/edit/{{id}}?organization={{type}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a href="/organizations/delete/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/organizations}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
