{{% BLOCKS }}
{{<layout}}
{{$content}}

{{{TypeForm}}}

{{/content}}

{{/layout}}

<script>
    $(document).ready(function () {


        $('.orgType').change(function () {
            rearrangeType();
        });
        /**
         * function to return zf2 parameters for selected organization
         * ex: returns /1/3 for 1st and 3rd orgs
         * @param {type} list
         * @returns {parameter|String}
         */
        function rearrangeType() {
            var sList = "";
            $('input[type=checkbox]').each(function () {
                var sThisVal = (this.checked ? "1" : "0");
                sList += (sList = "" ? sThisVal : "," + sThisVal);
            });
            $('#type_form_type').val(prepareTypes(sList));
        }
        /**
         * function converts binary array ex(0,1,1,0) to zf2 parameters
         * @param {type} list
         * @returns {parameter|String}
         */
        function prepareTypes(list) {
            var index = 1;
            var types = list.split(',');
            // remove 1st item cause its  ( '',x,x,x,x )
            types.splice(0, 1);
            parameter = '';
            //convert 1,0,1,1 -> 1/3/4
            for (i = 0; i < types.length; i++) {
                if (types[i] == 1) {
                    parameter += "/" + index;
                }
                index++;
            }
            return parameter;
        }
    });

</script>