{{% BLOCKS }}
{{<layout}}
{{$content}}

<div class="col-md-12 panel panel-default">
    <div class="col-md-6">
        <div class="panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{#translate}}Our Address{{/translate}}</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-6">
                    <iframe
                        width="203px"
                        height="185px"
                        frameborder="0" style="border:0"
                        src="http://maps.google.com/maps?v=2&f=q&ie=UTF8&t=m&iwloc=&q=303+Twin+Dolphin+Drive%2c+Redwood+City%2c+CA+94065%2c+USA&hl=en&z=14&source=s_q&output=embed" allowfullscreen>
                    </iframe>

                    <div>
                        <p>
                            <span>
                                <strong>USA:</strong>
                            </span>
                        </p>
                        <p>303 Twin Dolphin Drive, 6th Floor Redwood City CA 94065 US</p>
                        <p>Tel: +1.6506324570</p>
                        <p><a href="mailto:info@thinkcsi.com" target="_blank">info@thinkcsi.com</a></p>
                    </div>
                </div>
                <div class="col-md-6">
                    <iframe
                        width="203px"
                        height="185px"
                        frameborder="0" style="border:0"
                        src="https://www.google.com/maps/embed?origin=mfe&pb=!1m4!2m1!1sThinkCSI,+Al+Muhandis+Masaid+Al+Anqari,+Riyadh,+Riyadh+Province,+Saudi+Arabia!5e0!6i13!3m1!1sen!5m1!1sen" allowfullscreen>
                    </iframe>

                    <div>
                        <p>
                            <span>
                                <strong>Saudi Arabia:</strong>
                            </span>
                        </p>
                        <p>Riyadh, Sulaimaniah,</p>
                        <p>Mussaed Al Anqari St.
                        Abanamai Buildings, Block 2B 2nd Floor B16, B20</p>
                        <p>Tel: +966 92000 44 25</p>
                        <p><a href="mailto:info@thinkcsi.com" target="_blank">info@thinkcsi.com</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{#translate}}Send Us Message{{/translate}}</h3>
            </div>
            <div class="panel-body">
                {{{form}}}
            </div>
        </div>
    </div>
</div>
{{/content}}
{{/layout}}