{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/issues/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Issue{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading"><h2>{{#translate}}Reported Issues{{/translate}}</h2></div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Ticket No.{{/translate}}</th>
                <th>{{#translate}}Title{{/translate}}</th>
                <th>{{#translate}}Description{{/translate}}</th>
                <th>{{#translate}}Categories path{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#issues}}
            <tr>
                <td>{{id}}</td>
                <td>{{title}}</td>
                <td>{{description}}</td>
                <td>{{#parent3}}{{#parent2}}{{#parent1}}{{title}} > {{/parent1}}{{title}} > {{/parent2}}{{title}}{{/parent3}}</td>
                <td>{{statusText}}</td>
                <td>
                    <a href="/issues/view/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#isAdmin}}
                    {{#status}}
                    <a  onclick="toggleIssue(false, {{id}})"data-placement="left" title="{{#translate}}close{{/translate}}"><span class="glyphicon glyphicon-ban-circle"></span></a>
                    {{/status}}
                    {{^status}}
                    <a  onclick="toggleIssue(true, {{id}})"data-placement="left" title="{{#translate}}reopen{{/translate}}"><span class="glyphicon glyphicon-refresh"></span></a>
                    {{/status}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a  onclick="deleteIssue({{id}})"data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isAdmin}}
                </td>
            </tr>
            {{/issues}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > {{#translate}}Pages{{/translate}} :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}
{{$scripts}}
<script type="text/javascript">
            /**
             * function to delete issues
             * @param int id issue id
             */
            function deleteIssue(id) {
            message = '{{#translate}}Are you sure you want to delete this issue{{/translate}}';
                    bootbox.confirm(message + " ...?", function (result) {
                    if (result) {
                    window.location.assign('/issues/delete/' + id);
                    }
                    });
            }

            /**
             * function to toggle status of an issue
             * @param boolean status if isuue is closed or not 
             * @param int id issue id
             */
            function toggleIssue(status, id) {
            message = '';
            if(status){
                message = "{{#translate}}Are you sure you want to reopen this issue{{/translate}}";
                url = "/issues/reopen/";
            }else{
                message = "{{#translate}}Are you sure you want to close this issue{{/translate}}";
                url = "/issues/close/";
            }
           
            bootbox.confirm(message + " ...?", function (result) {
                if (result) {
                    window.location.assign(url + id);
                }
            });
    }
</script>
{{/scripts}}

{{/layout}}
