{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/issues/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Issue{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading"><h2>{{#translate}}Reported Issues{{/translate}}</h2></div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Title{{/translate}}</th>
                <th>{{#translate}}Description{{/translate}}</th>
                <th>{{#translate}}parents{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#issues}}
            <tr>
                <td>{{title}}</td>
                <td>{{description}}</td>
                <td>{{#parent3}}{{#parent2}}{{#parent1}}{{title}} > {{/parent1}}{{title}} > {{/parent2}}{{title}}{{/parent3}}</td>
                <td>{{statusText}}</td>
                <td>
                    <a href="/issues/view/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}View{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#isAdmin}}
                    {{#status}}
                    <a href="" data-toggle="modal" data-target="#closeIssue_{{id}}" data-placement="left" title="{{#translate}}close{{/translate}}"><span class="glyphicon glyphicon-ban-circle"></span></a>

                    <div class="modal fade" id="closeIssue_{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
                                </div>
                                <div class="modal-body">
                                    {{#translate}}Are you sure you want to close this issue{{/translate}} ?!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                                    <a  href="/issues/close/{{id}}" type="button" class="btn btn-primary">{{#translate}}Close Issue{{/translate}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {{/status}}
                    {{^status}}
                    <a href="" data-toggle="modal" data-target="#reopenIssue_{{id}}" data-placement="left" title="{{#translate}}reopen{{/translate}}"><span class=" glyphicon glyphicon-refresh"></span></a>

                    <div class="modal fade" id="reopenIssue_{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
                                </div>
                                <div class="modal-body">
                                    {{#translate}}Are you sure you want to reopen this issue{{/translate}} ?!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                                    <a  href="/issues/reopen/{{id}}" type="button" class="btn btn-primary">{{#translate}}Reopen Issue{{/translate}}</a>
                                </div>
                            </div>
                        </div>
                    </div>    
                    {{/status}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="" data-toggle="modal" data-target="#deleteIssue_{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    
                    <div class="modal fade" id="deleteIssue_{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
                                </div>
                                <div class="modal-body">
                                    {{#translate}}Are you sure you want to delete this issue{{/translate}} ?!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                                    <a  href="/issues/delete/{{id}}" type="button" class="btn btn-primary">{{#translate}}Delete Issue{{/translate}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {{/isAdmin}}
                </td>
            </tr>
            {{/issues}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > {{#translate}}Pages{{/translate}} :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}
{{/layout}}
