{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}New Issue{{/translate}}</h3>
    </div>
    <div class="panel-body">
        {{{trackerForm}}}
    </div><!-- body -->
</div><!-- panel -->

{{/content}}
{{/layout}}
<script>
    $(document).ready(function () {
        $categories = JSON.parse('{{{descriptions}}}');
        $('#issue_tracker_form_parent').change(function () {
            $('#category_description').remove();
            $selecedCategoryId = $(this).val();
            var result = $categories.filter(function (obj) {
                return obj.id == $selecedCategoryId;
            })[0];
            $(this).after('<p id="category_description" style="color:Red;">' + result.description + '</p>');
        });
    });
</script>
