{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}New Issue{{/translate}}</h3>
    </div>
    <div class="panel-body main-form  ">
        {{{openTag}}}
        <div class="row panel-border">
            <h2 class="sub-title-form">{{#translate}}ISSUE DATA {{/translate}}</h2>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-1 control-label required"  for="issue_tracker_form_parent">{{#translate}}{{parentLabel}}{{/translate}}</label>
                    <div class="col-sm-6">
                        {{{parent}}}
                        {{{parentError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-1 control-label required"  for="issue_tracker_form_title">{{#translate}}{{titleLabel}}{{/translate}}</label>
                    <div class="col-sm-6">
                        {{{title}}}
                        {{{titleError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-1 control-label"  for="issue_tracker_form_filePath">{{#translate}}{{filePathLabel}}{{/translate}}</label>
                    <div class="col-sm-6">
                        {{{filePath}}}
                        {{{filePathError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-1 control-label required"  for="issue_tracker_form_description">{{#translate}}{{descriptionLabel}}{{/translate}}</label>
                    <div class="col-sm-6">
                        {{{description}}}
                        {{{descriptionError}}}
                    </div>
                </div>
            </div>
            <input type="Submit" name="buttons[create]" class="pull-left btn-inline btn btn-success" value="Save">
            <input name="buttons[reset]" class="pull-left btn-inline btn btn-danger resetButton" type="button" value="Reset"></fieldset>
        </div>
        {{{closeTag}}}
    </div>

</div><!-- panel -->



{{/content}}
{{/layout}}
<script>
    $(document).ready(function () {
        $categories = JSON.parse('{{{descriptions}}}');
        $('#issue_tracker_form_parent').change(function () {
            $('#category_description').remove();
            $selecedCategoryId = $(this).val();
            var result = $categories.filter(function (obj) {
                return obj.id == $selecedCategoryId;
            })[0];
            $(this).after('<p id="category_description" style="color:Red;">' + result.description + '</p>');
        });
    });
</script>
