{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .user_pic{
        width: 40px;
        height: 40px;
    }
    #comment_form_comment{
        margin-top: -25px;
        margin-bottom: -10px;
    }
    #comment_form_Create{
        margin-bottom: -10px;
    }
</style>
{{#issue}}
{{#isAdmin}}
{{#status}}
<br><br><br>
<a href="" data-toggle="modal" data-target="#closeIssue"><button class="btn btn-sm btn-warning" data-placement="left">{{#translate}}Close Issue{{/translate}}</button></a>

<div class="modal fade" id="closeIssue" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
            </div>
            <div class="modal-body">
                {{#translate}}Are you sure you want to close this issue{{/translate}} ?!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                <a  href="/issues/close/{{id}}" type="button" class="btn btn-primary">{{#translate}}Close Issue{{/translate}}</a>
            </div>
        </div>
    </div>
</div>    
{{/status}}
{{^status}}
<a href="" data-toggle="modal" data-target="#reopenIssue"><button class="btn btn-sm btn-success">{{#translate}}Reopen Issue{{/translate}}</button></a>

<div class="modal fade" id="reopenIssue" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
            </div>
            <div class="modal-body">
                {{#translate}}Are you sure you want to reopen this issue{{/translate}} ?!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                <a  href="/issues/reopen/{{id}}" type="button" class="btn btn-primary">{{#translate}}Reopen Issue{{/translate}}</a>
            </div>
        </div>
    </div>
</div>    
{{/status}}
{{/isAdmin}}
<br><br><br>
<div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-10 issue_report">
        <div class="panel panel-info">
            <div class="panel-heading">{{title}}</div>
            <div class="panel-body">
                <p>{{description}}</p>
                <div class="row">
                    <div class="col-lg-6 pull-left">
                        <img class="user_pic"src="{{user.photo}}"/>
                        <span> asked by : {{user.firstName}} {{user.middleName}} {{user.lastName}}</span>
                        <div class="row">
                            <div class="col-6">
                            <h4>{{#translate}}Attachments{{/translate}}:</h4>
                                {{#filePath}}
                                <a href="{{.}}" download><span class=" glyphicon glyphicon-download-alt"></span></a>
                                {{/filePath}}
                                {{^filePath}}
                                <span class="error">{{#translate}}Issue has no attachments{{/translate}}</span>
                                {{/filePath}}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 pull-right">
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        {{#previousComments}}
        <div class="panel panel-success">
            <div class="panel-heading"><img class="user_pic"src="{{user.photo}}"/>&nbsp;&nbsp;<span>{{user.firstName}}&nbsp;{{user.lastName}}</span>
                {{#isAdmin}}
                <div class="pull-right">
                    <a class="edit_comment" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;
                    <a href="" title="{{#translate}}Delete{{/translate}}" data-toggle="modal" data-target="#deleteComment_{{id}}"><span class=" glyphicon glyphicon-remove"></span></a>

                    <div class="modal fade" id="deleteComment_{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{{#translate}}Warning{{/translate}}</h4>
                                </div>
                                <div class="modal-body">
                                    {{#translate}}Are you sure you want to delete this comment{{/translate}} ?!
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">{{#translate}}Dismiss this message{{/translate}}</button>
                                    <a  href="/issues/comments/remove/{{issue.id}}/{{id}}" type="button" class="btn btn-primary">{{#translate}}Delete comment{{/translate}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {{/isAdmin}}
                {{^isAdmin}}
                {{#commentCreator}}
                <div class="pull-right">
                    <a class="edit_comment" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                </div>
                {{/commentCreator}}
                {{/isAdmin}}
            </div>
            <div class="panel-body">
                <p class="comment_text">{{comment}}</p>
                <p class="comment_id" style="visibility: hidden">{{id}}</p>
            </div>
        </div>
        {{/previousComments}}
        {{#currentUser}}
        <div class="panel panel-success">
            <div class="panel-heading"><img class="user_pic"src="{{photo}}"/>&nbsp;&nbsp;<span>{{firstName}}&nbsp;{{lastName}}</span></div>
            <div class="panel-body">
                <p>{{{commentForm}}}</p>
            </div>
        </div>
        {{/currentUser}}
    </div>
    <div class="col-lg-1"></div>
</div>
{{/issue}}
{{/content}}
{{/layout}}
<script>
    $(document).ready(function () {
    $('.edit_comment').click(function () {
    $commentContainer = $(this).parents('.panel').find('p.comment_text');
            $comment = $commentContainer.text();
            $commentId = $commentContainer.next().text();
    {{#issue}}
    $form = '<form action="/issues/comments/edit/{{id}}/' + $commentId + '" method="POST" name="comment_form" class="form&#x20;edit_comment_form&#x20;form-horizontal"><dt>&nbsp;</dt><textarea name="comment" required="required" class="form-control" id="comment_form_comment_' + $commentId + '">' + $comment + '</textarea><div ><input type="hidden" name="id" id="comment_form_id" value="' + $commentId + '"></div><dt>&nbsp;</dt><input type="submit" name="Create" class="editComment&#x20;btn&#x20;btn-success" id="comment_form_Create" value="edit"></form>';
    {{/issue}}
            // removing hidden span with comment id 
            $commentContainer.next().remove();
            // creating the form with comment inside
            $commentContainer.after($form);
            // remove comment span
            $commentContainer.remove();
    });
            $(document).on("submit", ".edit_comment_form", function(e) {
    e.preventDefault(); // avoid to execute the actual submit of the form.
            $url = $(this).attr('action'); // the script where you handle the form input.
            $self = $(this);
            $.ajax({
            type: "POST",
                    url: $url,
                    data: $(this).serialize(), // serializes the form's elements.
                    dataType:'json',
            })
            .done(function(data) {
            $newComment = data.comment;
                    $newCommentId = data.id;
                    $self.parent('.panel-body').append('<p class="comment_text">' + $newComment + '</p> <p class="comment_id" style="visibility: hidden">' + $newCommentId + '</p>');
                    $self.remove();
            })
            .fail(function(data) {
            alert('{{#translate}}Bad request ... you cant edit this comment{{/translate}}.');
            });
    });
    });
</script>
