{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .user_pic{
        width: 40px;
        height: 40px;
    }
    #comment_form_comment{
        margin-top: -25px;
        margin-bottom: -10px;
    }
    #comment_form_Create{
        margin-bottom: -10px;
    }
</style>
{{#issue}}
{{#isAdmin}}
{{#status}}
<br><br><br>
<a  onclick="toggleIssue(false, {{id}})"data-placement="left" ><button class="btn btn-sm btn-warning" data-placement="left">{{#translate}}Close Issue{{/translate}}</button></a>
{{/status}}
{{^status}}
<a  onclick="toggleIssue(true, {{id}})"data-placement="left"><button class="btn btn-sm btn-success">{{#translate}}Reopen Issue{{/translate}}</button></a>
{{/status}}
{{/isAdmin}}
<br><br><br>
<div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-10 issue_report">
        <div class="panel panel-info">
            <div class="panel-heading">[{{id}}] {{title}}</div>
            <div class="panel-body">
                <p>{{description}}</p>
                <div class="row">
                    <div class="col-lg-6 pull-left">
                        <img class="user_pic"src="{{user.photo}}"/>
                        <span> asked by : {{user.firstName}} {{user.middleName}} {{user.lastName}}</span>
                        <div class="row">
                            <div class="col-6">
                                <h4>{{#translate}}Attachments{{/translate}}:</h4>
                                {{#filePath}}
                                <a href="{{.}}" download><span class=" glyphicon glyphicon-download-alt"></span></a>
                                {{/filePath}}
                                {{^filePath}}
                                <span class="error">{{#translate}}Issue has no attachments{{/translate}}</span>
                                {{/filePath}}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 pull-right">
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        {{#previousComments}}
        <div class="panel panel-success">
            <div class="panel-heading"><img class="user_pic"src="{{user.photo}}"/>&nbsp;&nbsp;<span>{{user.firstName}}&nbsp;{{user.lastName}}</span>
                
                <div class="pull-right">
                {{#isAdmin}}
                    <a class="edit_comment" onclick="editComment('#comment_text_{{id}}','{{id}}','{{issue.id}}')" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;
                    <a  title="{{#translate}}Delete{{/translate}}" onclick="deleteComment({{issue.id}}, {{id}})" ><span class=" glyphicon glyphicon-remove"></span></a>
                {{/isAdmin}}
                {{^isAdmin}}
                    {{#commentCreator}}
                    <a class="edit_comment" onclick="editComment('#comment_text_{{id}}','{{id}}','{{issue.id}}')" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{/commentCreator}}
                {{/isAdmin}}
                </div>
                <div class="panel-body">
                    <p id="comment_text_{{id}}" class="comment_text">{{comment}}</p>
                </div>
            </div>
            {{/previousComments}}
            {{#currentUser}}
            <div class="panel panel-success">
                <div class="panel-heading"><img class="user_pic"src="{{photo}}"/>&nbsp;&nbsp;<span>{{firstName}}&nbsp;{{lastName}}</span></div>
                <div class="panel-body">
                    <p>{{{commentForm}}}</p>
                </div>
            </div>
            {{/currentUser}}
        </div>
        <div class="col-lg-1"></div>
    </div>
    {{/issue}}
    {{/content}}
    {{/layout}}
    <script>
    $(document).ready(function () {
        $(document).on("submit", ".edit_comment_form", function(e) {
            e.preventDefault(); // avoid to execute the actual submit of the form.
            $url = $(this).attr('action'); // the script where you handle the form input.
            $self = $(this);
            $.ajax({
                type: "POST",
                url: $url,
                data: $(this).serialize(), // serializes the form's elements.
                dataType:'json',
            })
            .done(function(data) {
                $newComment = data.comment;
                $newCommentId = data.id;
                $self.parent('.panel-body').append('<p id="comment_text_' + $newCommentId + '" class="comment_text">' + $newComment + '</p>');
                $self.remove();
            })
            .fail(function(data) {
                alert('{{#translate}}Bad request ... you cant edit this comment{{/translate}}.');
            });
        });
    });
    
    function editComment(commentTextSelector, commentId, issueId){
        var commentContainer = $(commentTextSelector);
        var comment = $(commentTextSelector).text();
        var form = '<form action="/issues/comments/edit/' + issueId + '/' + commentId + '" method="POST" name="comment_form" class="form&#x20;edit_comment_form&#x20;form-horizontal"><dt>&nbsp;</dt><textarea name="comment" required="required" class="form-control" id="comment_form_comment_' + commentId + '">' + comment + '</textarea><div ><input type="hidden" name="id" id="comment_form_id" value="' + commentId + '"></div><dt>&nbsp;</dt><input type="submit" name="Create" class="editComment&#x20;btn&#x20;btn-success" id="comment_form_Create" value="edit"></form>';
        // creating the form with comment inside
        commentContainer.parent().append(form);
        // remove comment span
        commentContainer.remove();
    }
    
    /**
     * function to delete comments
     * @param int issueId issue id
     * @param int id comment id
     */
    function deleteComment(issueId, id) {
        message = '{{#translate}}Are you sure you want to delete this comment{{/translate}}';
        bootbox.confirm(message + " ...?", function (result) {
            if (result) {
                window.location.assign('/issues/comments/remove/' + issueId + '/' + id);
            }
        });
    }

    /**
     * function to toggle status of an issue
     * @param boolean status if isuue is closed or not 
     * @param int id issue id
     */
    function toggleIssue(status, id) {
        message = '';
        if (status){
            message = {{#translate}}"Are you sure you want to reopen this issue"{{/translate}};
            url = "/issues/reopen/";
        } else{
            message = {{#translate}}"Are you sure you want to close this issue"{{/translate}};
            url = "/issues/close/";
        }

        bootbox.confirm(message + " ...?", function (result) {
            if (result) {
                window.location.assign(url + id);
            }
        });
    }
    </script>
