{{% BLOCKS }}
{{<layout}}
{{$content}}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="/courses/edit/{{courseId}}" aria-controls="courseDetails">{{#translation}}Course Details{{/translation}}</a></li>
    <li role="presentation"><a href="/courses/evaluation/edit/{{courseId}}" aria-controls="courseEvaluation">{{#translation}}Course Evaluation{{/translation}}</a></li>
    <li role="presentation" class="active"><a href="/courses/resources/edit/{{courseId}}" aria-controls="courseResources">{{#translation}}Course Resources{{/translation}}</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="courseDetails">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{#translation}}Edit Course{{/translation}}</h3>
            </div>
            <div class="panel-body">
                {{{courseForm}}}
            </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="courseEvaluation">...</div>
    <div role="tabpanel" class="tab-pane active" id="courseResources">
        <br>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{#translation}}Upload Resources{{/translation}}</h3>
            </div>
            <div class="panel-body">
                {{{resourceForm}}}
            </div><!-- body -->
        </div><!-- panel -->
    </div>
</div>



{{/content}}
{{$scripts}}
<script>
    $(document).ready(function () {
    {{#addResourcesValidation}}
    addMoreResource('#resource_form_addMore', '#resource_form_name', '#resource_form_file', '{{name.value}}', '{{name.errorClass}}', '{{name.errorsMarkup}}', '{{file.errorClass}}', '{{file.errorsMarkup}}');
    {{/addResourcesValidation}}
    });
</script>
{{/scripts}}
{{/layout}}
