{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Edit Course Event{{/translate}}</h3>
    </div>
    <div class="panel-body main-form  ">
        {{{openTag}}}
        <div class="row panel-border">
            <h2 class="sub-title-form"> COURSE EVENT DATA</h2>

            {{!-- if course-event for a specific course --! }}
            {{#courseName}}
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-2 control-label required"  for="course_event_form_course">{{courseLabel}}</label>
                    <div class="col-sm-10">
                        {{{course}}}
                        {{{courseError}}}
                    </div>
                </div>
            </div>
            {{/courseName}}

            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="course_event_form_atp">{{atpLabel}}</label>
                    <div class="col-sm-9">
                        {{{atp}}}
                        {{{atpError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="course_event_form_ai">{{aiLabel}}</label>
                    <div class="col-sm-9">
                        {{{ai}}}
                        {{{aiError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="course_event_form_capacity">{{capacityLabel}}</label>
                    <div class="col-sm-5">
                        {{{capacity}}}
                        {{{capacityError}}}
                    </div>
                    <div class="col-sm-1">
                        {{{fullCapacity}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="course_event_form_studentsNo">{{studentsNoLabel}}</label>
                    <div class="col-sm-9">
                        {{{studentsNo}}}
                        {{{studentsNoError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label required" for="course_event_form_startDateHj">{{startDateHjLabel}}</label>
                    <div class="col-sm-9">
                        {{{startDateHj}}}
                        {{{startDateHjError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label required" for="course_event_form_startDate">{{startDateLabel}}</label>
                    <div class="col-sm-9">
                        {{{startDate}}}
                        {{{startDateError}}}
                    </div>
                </div> 
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label required" for="course_event_form_endDateHj">{{endDateHjLabel}}</label>
                    <div class="col-sm-9">
                        {{{endDateHj}}}
                        {{{endDateHjError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-sm-3 control-label required" for="course_event_form_endDate">{{endDateLabel}}</label>
                    <div class="col-sm-9">
                        {{{endDate}}}
                        {{{endDateError}}}
                    </div>
                </div> 
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label class="c-input control-label statement" for="course_event_form_hideFromCalendar">
                        {{{hideFromCalendar}}}
                        {{{hideFromCalendarError}}}
                        <span class="c-indicator" style="margin-left: 180%;margin-top: 10px;" ></span>
                        {{hideFromCalendarLabel}}
                    </label>
                </div>
            </div>
            <div class="form-group">
                {{{id}}}
                {{{idError}}}
            </div>
            <input type="Submit" name="buttons[create]" class="pull-left btn-inline btn btn-success" value="Save">
            <input name="buttons[reset]" class="pull-left btn-inline btn btn-danger resetButton" type="button" value="Reset"></fieldset>
        </div>
        {{{closeTag}}}
    </div>

</div>
{{/content}}
{{/layout}}
