{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/course-events/new{{#courseId}}/{{courseId}}{{/courseId}}"><button class="btn btn-small btn-success">Create new Course Event</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Course Events{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Name{{/translate}}</th>
                <th>{{#translate}}Start Date{{/translate}}</th>
                <th>{{#translate}}End Date{{/translate}}</th>
                <th>{{#translate}}Instructor{{/translate}}</th>
                <th>{{#translate}}ATP{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courseEvents}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td>{{course.name}}</td>
                <td>{{startDate}}</td>
                <td>{{endDate}}</td>
                <td>{{ai.firstName}} {{ai.lastName}}</td>
                <td>{{atp.commercialName}}</td>
                <td>{{statusText}}</td>
                <td>
                    <a href="/course-events/edit/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a onclick="deleteCourseEvent({{id}})" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/courseEvents}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
<script>
    function deleteCourseEvent(id){
            message = "{{#translate}}Are you sure you want to delete this course event{{/translate}} ..?!";
            url = '/course-events/delete/'+id;
            bootbox.confirm(message, function(result) {
                if (result){
                    window.location.assign(url);
                }
            });
    }    
</script>