{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    .cover_image{
        width: 250px;
        height: 200px;
    }
    .summary{
        margin-top: 3px;
    }
    .news_body{
        margin-top: 20px;
    }
</style>


{{#details}}
<div class="row">
    <div class="col-lg-3 main_pic">
        <div class="imageContainer">
            <img class="cover_image" src="/upload/pagePictures/{{picture.tmp_name}}"/>
        </div>
    </div>
    <div class=" col-lg-7 news_head">
        <blockquote>
            <h3>{{title}}</h3>
            <footer>
                <span>By: {{author}}</span><span class="pull-right">{{created}}</span>
            </footer>
        </blockquote>


        <div class="summary">
            {{summary}}
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-lg-12 news_body">
        {{{body}}}
    </div> 
</div>

<button type="button" class="btn btn-info" data-toggle="modal" data-target=".bs-example-modal-lg">Send to friend</button>

<a href="/pdf/{{id}}"><button type="button" class="btn btn-success download_pdf">Download</button></a>



<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Send to friend</h3>
                </div>
                <div class="panel-body">
                    {{{form}}}
                </div>
            </div>
        </div>
    </div>
</div>
{{/details}}


{{/content}}
{{/layout}}
<script>
    $(document).ready(function () {
        // hiding unneeded fields
        $('#contact_us_form_name').removeAttr('required').parent().hide();
        $('#contact_us_form_subject').removeAttr('required').parent().hide();
        $('#contact_us_form_message').removeAttr('required').parent().hide();
    });
</script>