{{% BLOCKS }}
{{<layout}}

{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Edit Resource{{/translate}}</h3>
    </div>
    <!----------->
    <div class="panel-body main-form  ">
        {{{openTag}}}
        <div class="row panel-border">
            <h2 class="sub-title-form">{{#translate}}EDIT RESOURCE'S DATA{{/translate}}</h2>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_course">{{#translate}}{{courseLabel}}{{/translate}}</label>
                    <div class="col-sm-9">
                        {{{course}}}
                        {{{courseError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_type">{{#translate}}{{typeLabel}}{{/translate}}</label>
                    <div class="col-sm-9">
                        {{{type}}}
                        {{{typeError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_name">{{#translate}}{{nameLabel}}{{/translate}}</label>
                    <div class="col-sm-9">
                        {{{name}}}
                        {{{nameError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_nameAr">{{#translate}}{{nameArLabel}}{{/translate}}</label>
                    <div class="col-sm-9">
                        {{{nameAr}}}
                        {{{nameArError}}}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_file">{{#translate}}{{fileLabel}}{{/translate}}</label>
                    <div class="col-sm-3">
                        {{{file}}}
                        {{{fileError}}}
                    </div>
                    <div class="col-sm-3">
                        <b><p>Supported Extensions: zip,pdf,ppt,pptx</p></b>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label  class="col-sm-3 control-label required"  for="resource_form_status">{{#translate}}{{statusLabel}}{{/translate}}</label>
                    <div class="col-sm-3">
                        {{{status}}}
                        {{{statusError}}}
                    </div>
                </div>
            </div>
        </div>
        {{{buttons}}}
        {{{closeTag}}}
    </div>
    <!----------->

</div>
{{/content}}
{{/layout}}
