{{% BLOCKS }}
{{<layout}}
{{$content}}
<style>
    td{
        width: 500px;
    }
</style>
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="/courses/edit/{{courseId}}" aria-controls="courseDetails" >Course Details</a></li>
    <li role="presentation"><a href="/courses/evaluation/edit/{{courseId}}" aria-controls="courseEvaluation">Course Evaluation</a></li>
    <li role="presentation" class="active"><a href="#courseResources" aria-controls="courseResources" role="tab" data-toggle="tab">Course Resources</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="courseDetails">...</div>
    <div role="tabpanel" class="tab-pane" id="courseEvaluation">...</div>
    <div role="tabpanel" class="tab-pane active" id="courseResources">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Edit Resources</h3>
            </div>
            <div class="panel-body">
                <a href="/courses/resources/new/{{courseId}}"><button class="btn btn-small btn-success">{{#translate}}Bulk upload Resources{{/translate}}</button></a>
                <br><br>
                {{#resources.count}}
                <form id="resourcesForm" action="" method="POST" >
                    <div class="panel panel-default">
                        <div class="panel-heading">{{#translate}}Resources{{/translate}}</div>
                        <!-- Table -->
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>{{#translate}}Name{{/translate}}</th>
                                    <th>{{#translate}}Name in Arabic{{/translate}}</th>
                                    <th>{{#translate}}Type{{/translate}}</th>
                                    <th>{{#translate}}File{{/translate}}</th>
                                    <th colspan="2">{{#translate}}Actions{{/translate}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {{#resources}}
                                <tr id ="{{id}}" class="{{^status}}container-inactive{{/status}}">
                                    <td>
                                        <input type="text" class="form-control editableInput resourceName" value="{{name}}">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control editableInput resourceNameAr" value="{{nameAr}}">
                                    </td>
                                    <td>
                                        <select class="resourceType resourceType-{{id}} form-control editableInput">
                                            {{#types}}
                                            <option value="{{id}}">{{#translate}}{{title}}{{/translate}}</option>
                                            {{/types}}
                                        </select>
                                    </td>
                                    <td><a target="_blank" href="/courses/resources/download/{{id}}" >{{#translate}}Download{{/translate}}</a></td>
                                    <td>
                                        <button  type="button" class="btn btn-danger removeResource" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}">{{#translate}}Remove{{/translate}}</a>
                                    </td>
                                </tr>
                                {{/resources}}
                                </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <button type="submit" class="btn btn-primary" name="submit" >{{^isAdminUser}}Submit for admin approval{{/isAdminUser}}{{#isAdminUser}}Save Resources{{/isAdminUser}} </button>
                </form>
                {{/resources.count}}
                {{^resources.count}}
                <b>No Resources Yet !</b>
                {{/resources.count}}
            </div>
        </div>
    </div>
</div>

{{/content}}
{{$scripts}}
<script>
    $(document).ready(function () {
    {{#resources}}
    $(".resourceType-{{id}}").val('{{type.id}}');
    {{/resources}}

        $('.removeResource').click(function () {
            var removeButton = $(this);
            bootbox.confirm("Are you sure you want to delete the resource ?", function (result) {
                if (result) {
                    var resourceId = removeButton.closest('tr').attr("id");
                    $.ajax({
                        dataType: "json",
                        url: "/courses/resources/delete/" + resourceId,
                        data: "",
                    });
                    removeButton.closest('tr').remove();
                }
            });
        });
        /**
         * by this implementation we will only use editedName
         */
        $('.editableInput').change(function () {
            var inputType = $(this).attr('type');
            var resourceId = $(this).closest('tr').attr('id');
            var parent = $(this).closest('tr');
            //text field
            if (inputType === "text") {
                if ($(this).hasClass('resourceName')) {
                    $(this).attr('name', 'editedName[' + resourceId + ']');
                }
                else if ($(this).hasClass('resourceNameAr')) {
                    $(this).attr('name', 'editedNameAr[' + resourceId + ']');
                }
            }
            // combobox
            else {
                $(this).attr('name', 'editedType[' + resourceId + ']');
            }
        });
    });
</script>
{{/scripts}}
{{/layout}}
