{{% BLOCKS }}
{{<layout}}
{{$content}}

{{^processResult}}
<div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{#translate}}Process failed to complete{{/translate}}!
</div>
{{/processResult}}

<a href="/resources/new{{#courseId}}/{{courseId}}{{/courseId}}"><button class="btn btn-small btn-success">{{#translate}}Bulk upload Resources{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Resources{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Name{{/translate}}</th>
                <th>{{#translate}}Name in Arabic{{/translate}}</th>
                <th>{{#translate}}Type{{/translate}}</th>
                <th>{{#translate}}Course{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#resources}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td><a target="_blank" href="/resources/download/{{id}}" >{{name}}</a></td>
                <td><a target="_blank" href="/resources/download/{{id}}" >{{nameAr}}</a></td>
                <td>{{type.title}}</td>
                <td>{{course.name}}</td>
                <td>{{statusText}}</td>

                <td>  
                    {{#isInstructor}}
                    <a href="/resources/edit/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#isAdminUser}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#" data-href="/resources/delete/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" onclick="deleteResourcePhysically($(this))" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isAdminUser}}
                    {{/isInstructor}}
                    

                </td>
            </tr>
            {{/resources}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
