{{% BLOCKS }}
{{<layout}}
{{$content}}

{{^processResult}}
<div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{#translate}}Process failed to complete{{/translate}}!
</div>
{{/processResult}}

<a href="/courses/resources/new{{#courseId}}/{{courseId}}{{/courseId}}"><button class="btn btn-small btn-success">{{#translate}}Bulk upload Resources{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Resources{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Name{{/translate}}</th>
                <th>{{#translate}}Type{{/translate}}</th>
                <th>{{#translate}}Course{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#resources}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td>
                    <a target="_blank" href="/courses/resources/download/{{id}}" >
                        {{#locale_en}}
                        {{name}}
                        {{/locale_en}}
                        {{#locale_ar}}
                        {{nameAr}}
                        {{/locale_ar}}
                    </a>
                </td>
                <td>{{#translate}}{{type.title}}{{/translate}}</td>
                <td>
                    {{#locale_en}}
                    {{course.name}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{course.nameAr}}
                    {{/locale_ar}}
                </td>
                <td>{{#translate}}{{statusText}}{{#translate}}</td>
                <td>  
                    {{#isInstructor}}
                    <a href="/courses/resources/edit/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#isAdminUser}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#" data-href="/courses/resources/delete/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" onclick="deleteResourcePhysically($(this))" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isAdminUser}}
                    {{/isInstructor}}
                </td>
            </tr>
            {{/resources}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
