{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Privileges of role{{/translate}} <strong>{{role.name}}</strong></div>

    <form action="/roles/privileges/{{role.id}}" method="post">
        {{#modulesRoutes}}

        <fieldset>
            <legend>{{module}}</legend>
            <input id="privilege-{{module}}" class="checkAllModuleRoutes" data-module="{{module}}" type="checkbox"/>
            <label for="privilege-{{module}}">{{#translate}}{{#translate}}Check All{{/translate}}{{/translate}}</label>
            <div class="input-group-sm checkAll-{{module}}">
                {{#routes}}

                <input id="privilege-{{module}}-{{name}}" name="privileges[]" type="checkbox" value="{{module}}-{{name}}" {{#checked}}checked{{/checked}}/>
                <label for="privilege-{{module}}-{{name}}">{{#translate}}{{name}}{{/translate}}</label>

                {{/routes}}
            </div>
        </fieldset>
        {{/modulesRoutes}}

        <input type="submit" type="button" class="btn-large btn btn-success" value="Save"/>
    </form>

</div>

{{/content}}
{{/layout}}
