{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="main-holder">
    <div class="container">
        <div class="page-container">
            <div class="row">
                <div class="panel panel-default ">
                    <div class="panel-heading">
                        <h3>Edit Menu-Item</h3>
                    </div>
                    <div class="panel-body main-form  ">
                        {{{openTag}}}
                        <div class="row panel-border">
                            <h2 class="sub-title-form"> MENU Item DATA</h2>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_title">{{titleLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{title}}}
                                        {{{titleError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_titleAr">{{titleArLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{titleAr}}}
                                        {{{titleArError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_type">{{typeLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{type}}}
                                        {{{typeError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 menu-item-type-container">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_page">{{pageLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{page}}}
                                        {{{pageError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 menu-item-type-container">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_directUrl">{{directUrlLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{directUrl}}}
                                        {{{directUrlError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_optgroup-parent">{{optgroup-parentLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{optgroup-parent}}}
                                        {{{optgroup-parentError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_weight">{{weightLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{weight}}}
                                        {{{weightError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label  class="col-sm-2 control-label"  for="menu_item_form_status">{{statusLabel}}</label>
                                    <div class="col-sm-9">
                                        {{{menu}}}
                                        {{{status}}}
                                        {{{id}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-sm-9">
                                        {{{buttons}}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{{closeTag}}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{/content}}
{{$scripts}}
<script type="text/javascript" src="/js/menuItem.js"></script>
<script type="text/javascript">
$(function () {
    $('.menu_item_type:checked').change();
});
</script>
{{/scripts}}

{{/layout}}
