{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/cms/menuitem/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Menu Item{{/translate}}</a>
<br><br>
<div class="panel-default">

    <div class="panel-heading">{{#translate}}Filter Menu Items{{/translate}}</div>
    {{{filterForm}}}
</div>
<br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Menu Items{{/translate}}</div>


    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                {{#locale_en}}
                    <th>{{#translate}}Title{{/translate}}</th>
                {{/locale_en}}
                {{#locale_ar}}
                    <th>{{#translate}}Title in Arabic{{/translate}}</th>
                {{/locale_ar}}
                <th>{{#translate}}Menu Item Parent{{/translate}}</th>
                <th>{{#translate}}Page Path{{/translate}}</th>
                <th>{{#translate}}Direct Url{{/translate}}</th>
                <th>{{#translate}}Menu{{/translate}}</th>
                <th>{{#translate}}Sort order{{/translate}}</th>
                <th>{{#translate}}Status{{/translate}}</th>
                <th>{{#translate}}Menu Status{{/translate}}</th>
                <th>{{#translate}}Created{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#menuItems}}
            <tr class="{{^status}}container-inactive{{/status}} {{^menu.status}}container-inactive{{/menu.status}}" >
                {{#locale_en}}
                    <td>{{title}}</td>
                {{/locale_en}}
                {{#locale_ar}}
                    <td>{{titleAr}}</td>
                {{/locale_ar}}
                <td>
                    {{#parent}}
                        {{#locale_en}}
                            {{parent.title}}
                        {{/locale_en}}
                        {{#locale_ar}}
                            {{parent.titleAr}}
                        {{/locale_ar}}
                    {{/parent}}
                    {{^parent}}
                    Root
                    {{/parent}}
                </td>
                <td>{{page.path}}</td>
                <td>{{directUrl}}</td>
                {{#locale_en}}
                    <td>{{menu.title}}</td>
                {{/locale_en}}
                {{#locale_ar}}
                    <td>{{menu.titleAr}}</td>
                {{/locale_ar}}
                <td>{{weight}}</td>
                <td>{{statusText}}</td>
                <td>{{menu.statusText}}</td>
                <td>{{created}}</td>
                <td>
                    <a href="/cms/menuitem/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a onclick="toogleMenuItem(false, {{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Deactivate{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{^status}}
                    &nbsp;&nbsp;&nbsp;
                    <a onclick="toogleMenuItem(true, {{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Activate{{/translate}}"><span class="glyphicon glyphicon-arrow-up"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/menuItems}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{#hasPages}}
<div class="pagination-bar">
    <p > {{#translate}}Pages{{/translate}} :  </p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="pagination">
        {{#previousPageNumber}}
        <li >
            <a href="?page={{previousPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-left"></span></a>
        </li>
        {{/previousPageNumber}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{#pageNumbers}}
        <li {{#isCurrent}}class="active"{{/isCurrent}} >
            <a href="?page={{pageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}">{{pageNumber}}</a>
        </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {{/pageNumbers}}
        {{#nextPageNumber}}
        <li >
            <a href="?page={{nextPageNumber}}{{#filterQuery}}&{{filterQuery}}{{/filterQuery}}"><span class="glyphicon glyphicon-menu-right"></span></a>
        </li>
        {{/nextPageNumber}}
    </ul>
</div>
<br>
{{/hasPages}}
{{/content}}
{{/layout}}
<script>
            function toogleMenuItem(status, id){
            message = '';
                    url = '';
                    if (status){
            message = "{{#translate}}Are you sure you want to activate this menu item{{/translate}} ..?!";
                    url = '/cms/menuitem/activate/' + id;
            } else{
            message = "{{#translate}}Are you sure you want to deactivate this menu item{{/translate}} ..?!";
                    url = '/cms/menuitem/deactivate/' + id;
            }
            bootbox.confirm(message, function(result) {
            if (result){
            window.location.assign(url);
            }
            });
            }
</script>

