{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="main-holder">
    <div class="container">
        <div class="page-container">
            <div class="row">
                <div class="panel panel-default ">
                    <div class="panel-heading">
                        <h3>{{#translate}}New Menu-Item{{/translate}}</h3>
                    </div>
                    <div class="panel-body main-form  ">
                        {{{openTag}}}
                        <div class="row panel-border">
                            <h2 class="sub-title-form">{{#translate}}MENU Item DATA{{/translate}}</h2>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_title">{{#translate}}{{titleLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{title}}}
                                        {{{titleError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_titleAr">{{#translate}}{{titleArLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{titleAr}}}
                                        {{{titleArError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_type">{{#translate}}{{typeLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{type}}}
                                        {{{typeError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 menu-item-type-container">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_page">{{#translate}}{{pageLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{page}}}
                                        {{{pageError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 menu-item-type-container">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_directUrl">{{#translate}}{{directUrlLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{directUrl}}}
                                        {{{directUrlError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_optgroup-parent">{{#translate}}{{optgroup-parentLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{optgroup-parent}}}
                                        {{{optgroup-parentError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  class="col-sm-3 control-label required"  for="menu_item_form_weight">{{#translate}}{{weightLabel}}{{/translate}}</label>
                                    <div class="col-sm-9">
                                        {{{weight}}}
                                        {{{weightError}}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-md-12 c-input control-label statement" for="menu_item_form_status">
                                        {{{status}}}
                                        {{{statusError}}}
                                        <span class="c-indicator col-md-offset-3" ></span>
                                        {{statusLabel}}
                                    </label>
                                </div>
                            </div>
                            {{{menu}}}
                            {{{id}}}
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-sm-9">
                                        {{{buttons}}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{{closeTag}}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{/content}}
{{$scripts}}
<script type="text/javascript" src="/js/menuItem.js"></script>
{{/scripts}}
{{/layout}}
