{{% BLOCKS }}
{{<layout}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>New Resource</h3>
    </div>
    <div class="panel-body">
        {{{resourceForm}}}
    </div><!-- body -->
</div><!-- panel -->

{{/content}}
{{$scripts}}
<script>
    $(document).ready(function () {
        {{#addResourcesValidation}}
            addMoreResource('#resource_form_addMore', '#resource_form_name', '#resource_form_file', '{{name.value}}', '{{name.errorClass}}' , '{{name.errorsMarkup}}', '{{file.errorClass}}' , '{{file.errorsMarkup}}');
        {{/addResourcesValidation}}
    });
</script>
{{/scripts}}
{{/layout}}
