{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/cms/page/new"class="btn btn-small btn-success create-new">Create new Page</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Pages</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Menu Title</th>
                <th>Menu Item Parent</th>
                <th>Path</th>
                <th>Status</th>
                <th>Menu Status</th>
                <th>Created</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#pages}}
            <tr class="{{^menuItem.status}}container-inactive{{/menuItem.status}} {{^menuItem.menu.status}}container-inactive{{/menuItem.menu.status}}" >
                <td>{{title}}</td>
                <td>{{menuItem.title}}</td>
                <td>
                    {{#menuItem.parent}}
                    {{menuItem.parent.title}}
                    {{/menuItem.parent}}
                    {{^menuItem.parent}}
                    Root
                    {{/menuItem.parent}}
                </td>
                <td>{{menuItem.path}}</td>
                <td>{{menuItem.statusText}}</td>
                <td>{{menuItem.menu.statusText}}</td>
                <td>{{created}}</td>
                <td>
                    <a href="/cms/page/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#menuItem.status}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/cms/page/delete/{{id}}" class="delete_row" data-toggle="tooltip" data-placement="left" title="Delete"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/menuItem.status}}
                    {{#isAdminUser}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/cms/page/history/{{id}}" data-toggle="tooltip" data-placement="left" title="History"><span class="glyphicon glyphicon-time"></span></a>
                    {{/isAdminUser}}
                </td>
            </tr>
            {{/pages}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
