{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/cms/menu/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Menu{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Menus{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                {{#locale_en}}                
                <th>{{#translate}}Title{{/translate}}</th>
                {{/locale_en}}
                {{#locale_ar}}
                <th>{{#translate}}Title in Arabic{{/translate}}</th>
                {{/locale_ar}}
                <th>{{#translate}}Status{{/translate}}</th>
                <th>{{#translate}}Created{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#menus}}
            <tr class="{{^status}}container-inactive{{/status}}">
                {{#locale_en}}
                <td>{{title}}</td>
                {{/locale_en}}
                {{#locale_ar}}
                <td>{{titleAr}}</td>
                {{/locale_ar}}
                <td>{{statusText}}</td>
                <td>{{created}}</td>
                <td>
                    <a href="/cms/menu/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a onclick="toogleMenu(false,{{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Deactivate{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                    {{^status}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a onclick="toogleMenu(true,{{id}})" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Activate{{/translate}}"><span class="glyphicon glyphicon-arrow-up"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/menus}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
<script>

    function toogleMenu(status, id){
            message = '';
            url = '';
            if (status){
                message = "{{#translate}}Are you sure you want to activate this menu{{/translate}} ..?!";
                url = '/cms/menu/activate/' + id;
            } else{
                message = "{{#translate}}Are you sure you want to deactivate this menu{{/translate}} ..?!";
                url = '/cms/menu/deactivate/' + id;
            }
            bootbox.confirm(message, function(result) {
                if (result){
                    window.location.assign(url);
                }
            });
    }
</script>    