{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/roles/new"class="btn btn-small btn-success create-new">{{#translate}}Create new Role{{/translate}}</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Roles{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Title{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#roles}}
            <tr>
                <td>{{name}}</td>
                <td>
                    <a href="/roles/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit{{/translate}}"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;
                    <a href="/roles/privileges/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Privileges{{/translate}}"><span class="glyphicon glyphicon-eye-open"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/roles/delete/{{id}}" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
            {{/roles}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
