{{% BLOCKS }}
{{<layout}}
{{$content}}
{{#page}}
<a href="/cms/page" data-toggle="tooltip" data-placement="left" title="{{#translate}}Pages{{/translate}}"><button class="btn btn-small btn-primary"><span class="glyphicon glyphicon-arrow-left"></span></button></a>
<a href="/cms/page/edit/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Edit Page{{/translate}}"><button class="btn btn-small btn-success">Edit Page</button></a>
{{/page}}
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Pages History{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Username{{#translate}}</th>
                <th>{{#translate}}Data{{#translate}}</th>
                <th>{{#translate}}Taken Action{{#translate}}</th>
                <th>{{#translate}}Version{{#translate}}</th>
                <th>{{#translate}}Stored at{{#translate}}</th>
                <th colspan="2">{{#translate}}Actions{{#translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#logs}}
            <tr>
                <td>{{username}}</td>
                <td>
                    {{#data}}
                    <table class="table">
                        <tr>
                            <td>Title</td><td>{{title}}</td>
                        </tr>
                        <tr>
                            <td>Path</td><td>{{path}}</td>
                        </tr>
                        <tr>
                             <td>
                                 Body&nbsp;&nbsp;<a href="#" class="expandBody"><span class="glyphicon glyphicon-folder-open" title="{{#translate}}Expand Body{{/translate}}"></span></a>
                                 &nbsp;&nbsp;<a href="#" class="shortenBody"><span class="glyphicon glyphicon-folder-close" title="{{#translate}}Shorten Body{{/translate}}"></span></a>
                             </td>
                             <td hidden="">
                                 {{{body}}}
                             </td>
                        </tr>
                    </table>
                    {{/data}}
                </td>
                <td>{{action}}</td>
                <td>{{version}}</td>
                <td>{{loggedAt}}</td>
                <td>
                    {{^isLast}}
                    <a href="/version/restore/cmsPageHistory/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Restore{{/translate}}"><span class="glyphicon glyphicon-save"></span></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="/version/delete/cmsPageHistory/{{id}}" class="delete_row" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-trash"></span></a>
                    {{/isLast}}
                </td>
            </tr>
            {{/logs}}
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
<script>
    $(document).ready(function () {
        $('.shortenBody').each(function(){
           $(this).hide(); 
        });
        
        $('.expandBody').click(function () {
            $(this).parent().next().show();
            $(this).hide();
            $(this).next().show();
        });
        
        $('.shortenBody').click(function () {
            $(this).parent().next().hide();
            $(this).hide();
            $(this).prev().show();
        });
    });
</script>
