Feature: Users
    Testing guest, user and admin available operations

Scenario: guest register without required fields
    Given I am on "/users/new"
        And I fill in "user_form_username" with ""
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with ""
        And I fill in "confirmEmail" with ""
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with ""
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with ""
        And I fill in "identificationExpiryDateHj" with ""
        And I fill in "dateOfBirth" with ""
        And I fill in "dateOfBirthHj" with ""
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "Value is required and can't be empty" 24 times
        And I should see "Latitude is required"
        And I should see "Longitude is required"
        And I should see "You must agree to the privacy statement"

Scenario: guest register without type
    Given I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"

Scenario: guest register with invalid fields
    Given I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyy"
        And I fill in "email" with "justfortestuser_certigate@gmail.com"
        And I fill in "confirmEmail" with "yyyy"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "This username is already in use"
        And I should see "This email address is already in use"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long" 2 times
        And I should see "File has an incorrect extension"
        And I should see text matching "Please enter valid (phone|mobile) number" 2 times
        And I should see "The input does not appear to be a valid date" 4 times

Scenario: guest register with failed confirmation fields
    Given I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyyyyyyyyyy"
        And I fill in "email" with "justfortestuser_certigate"
        And I fill in "confirmEmail" with "justfortestuser_certigate@gmail.com"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long"
        And I should see "password doesnt match"
        And I should see "email doesnt match"

Scenario: guest register with multiple types with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I should see 1 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "justForTestUserx"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigatex@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUserx"

Scenario: guest register with instructor type with agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser2"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate2@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate2@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "Instructor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser2"

Scenario: instructor forbidden new users registration
    Given I mock the login session with "justForTestUser2" "veryStrongP@$$w0rd"
        And I am on "/users/new"
    Then I should be on "/noaccess"

Scenario: guest register with instructor type without agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser3"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate3@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate3@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Instructor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser3"

Scenario: guest register with student type with agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser4"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate4@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate4@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Student"
        And I check "studentStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser4"

Scenario: student forbidden new users registration
    Given I mock the login session with "justForTestUser4" "veryStrongP@$$w0rd"
        And I am on "/users/new"
    Then I should be on "/noaccess"

Scenario: guest register with student type without agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser5"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate5@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate5@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Student"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser5"

Scenario: guest register with proctor type with agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser6"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate6@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate6@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Proctor"
        And I check "proctorStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser6"

Scenario: proctor forbidden new users registration 
    Given I mock the login session with "justForTestUser6" "veryStrongP@$$w0rd"
        And I am on "/users/new"
    Then I should be on "/noaccess"

Scenario: guest register with proctor type without agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser7"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate7@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate7@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser7"

Scenario: guest register with training manager type with agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser8"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate8@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate8@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Training Manager"
        And I check "trainingManagerStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser8"

Scenario: guest register with training manager type without agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser9"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate9@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate9@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Training Manager"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser9"

Scenario: guest register with testing center admin type with agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser10"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate10@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate10@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Test Center Administrator"
        And I check "testCenterAdministratorStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser10"

Scenario: guest register with testing center admin type without agreement with autologin
    Given I am on "/users/new"
        And I should see 2 "input[name='username']" elements
        And I fill in "user_form_username" with "justForTestUser11"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate11@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate11@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "Test Center Administrator"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser11"

Scenario: training manager register new user with multiple types without autologin
    Given I mock the login session with "justForTestUser8" "veryStrongP@$$w0rd"
        And I am on "/users/new"
        And I should see 1 "input[name='username']" elements
        And I should see 1 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "justForTestUserx2"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigatex2@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex2@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser8"

Scenario: testing center admin register new user with multiple types without autologin
    Given I mock the login session with "justForTestUser10" "veryStrongP@$$w0rd"
        And I am on "/users/new"
        And I should see 1 "input[name='username']" elements
        And I should see 1 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "justForTestUserx3"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigatex3@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex3@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "justForTestUser10"

Scenario: admin register new user with multiple types without autologin
    Given I mock the login session
        And I am on "/users/new"
        And I should see 1 "input[name='username']" elements
        And I should see 2 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "justForTestUserx4"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigatex4@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex4@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/users"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "admin"

Scenario: user can view his/ her details
    Given I mock the login session with "user" "useruser"
        And I am on "/users/more/2"
    Then I should be on "/users/more/2"
        And I should see "User Details"

Scenario: user can not view others' details
    Given I mock the login session with "user" "useruser"
        And I am on "/users/more/3"
    Then I should be on "/noaccess"

Scenario: user can not edit others' details
    Given I mock the login session with "user" "useruser"
        And I am on "/users/edit/3"
    Then I should be on "/noaccess"

Scenario: user can edit his/ her details without autologin
    Given I mock the login session with "user" "useruser"
        And I am on "/users/edit/2"
        And I should see 1 "input[name='username']" elements
        And I should see 1 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "user"
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with "justfortestuser_certigatex5@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex5@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "user"

Scenario: user can not delete himself/herself
    Given I mock the login session with "user" "useruser"
        And I am on "/users/delete/2"
    Then I should be on "/noaccess"

Scenario: user can not delete others
    Given I mock the login session with "user" "useruser"
        And I am on "/users/delete/3"
    Then I should be on "/noaccess"

Scenario: user can not activate himself/herself
    Given I mock the login session with "user" "useruser"
        And I am on "/users/activate/2"
    Then I should be on "/noaccess"

Scenario: user can not activate others
    Given I mock the login session with "user" "useruser"
        And I am on "/users/activate/3"
    Then I should be on "/noaccess"

Scenario: user can not list users
    Given I mock the login session with "user" "useruser"
        And I am on "/users"
    Then I should be on "/noaccess"

Scenario: admin can delete others
    Given I mock the login session
        And I am on "/users"
        And I perform "Delete" action on row with "user" value
    Then I should be on "/users"

Scenario: user can not login while deleted
    Given I mock the login session with "user" "useruser"
    Then I should be on "/sign/in"

Scenario: admin can activate others
    Given I mock the login session
        And I am on "/users"
        And I perform "Activate" action on row with "user" value
    Then I should be on "/users"

Scenario: admin can view his/ her details
    Given I mock the login session
        And I am on "/users/more/1"
    Then I should be on "/users/more/1"
        And I should see "User Details"

Scenario: admin can not view others' details
    Given I mock the login session
        And I am on "/users/more/2"
    Then I should be on "/users/more/2"
        And I should see "User Details"

Scenario: admin can list users
    Given I mock the login session
        And I am on "/users"
    Then I should see "Users"
        And I should see "First Name"
        And I should see "Last Name"
        And I should see "User Name"
        And I should see "Status"
        And I should see "Actions"
        And I should see "admin"
        And I should see "user"
        And I should see "justForTestUser"

Scenario: admin can edit user with multiple types ,then delete that user
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "user" value
    Then I should see 1 "input[name='username']" elements
        And I should see 2 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "user"
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with "justfortestuser_certigatex6@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigatex6@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I check "Admin"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/users"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I perform "Delete" action on row with "user" value
    Then I should be on "/users"

Scenario: admin -user with admin role- can not login while deleted
    Given I mock the login session with "user" "useruser"
    Then I should be on "/sign/in"

Scenario: admin register new user without required fields
    Given I mock the login session
        And I am on "/users/new"
        And I fill in "user_form_username" with ""
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with ""
        And I fill in "confirmEmail" with ""
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with ""
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with ""
        And I fill in "identificationExpiryDateHj" with ""
        And I fill in "dateOfBirth" with ""
        And I fill in "dateOfBirthHj" with ""
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "Value is required and can't be empty" 24 times
        And I should see "Latitude is required"
        And I should see "Longitude is required"
        And I should see "You must agree to the privacy statement"

Scenario: admin register new user without type
    Given I mock the login session
        And I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser12"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate12@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate12@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/users"

Scenario: admin register new user with invalid fields
    Given I mock the login session
        And I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyy"
        And I fill in "email" with "justfortestuser_certigate@gmail.com"
        And I fill in "confirmEmail" with "yyyy"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "This username is already in use"
        And I should see "This email address is already in use"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long" 2 times
        And I should see "File has an incorrect extension"
        And I should see text matching "Please enter valid (phone|mobile) number" 2 times
        And I should see "The input does not appear to be a valid date" 4 times

Scenario: admin register new user with failed confirmation fields
    Given I mock the login session
        And I am on "/users/new"
        And I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyyyyyyyyyy"
        And I fill in "email" with "justfortestuser_certigate"
        And I fill in "confirmEmail" with "justfortestuser_certigate@gmail.com"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Create"
        And I should be on "/users/new"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long"
        And I should see "password doesnt match"
        And I should see "email doesnt match"

Scenario: admin edit user without required fields
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "tmuser" value
    Then I fill in "user_form_username" with ""
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with ""
        And I fill in "confirmEmail" with ""
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with ""
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with ""
        And I fill in "identificationExpiryDateHj" with ""
        And I fill in "dateOfBirth" with ""
        And I fill in "dateOfBirthHj" with ""
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I select "-- Select --" from "country"
        And I select "-- Select --" from "nationality"
        And I select "-- Select --" from "language"
        And I uncheck "privacyStatement"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/users/edit/3"
        And I should see "Value is required and can't be empty" 20 times
        And I should see "Latitude is required"
        And I should see "Longitude is required"
        And I should see "You must agree to the privacy statement"

Scenario: admin edit user without type
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "tcauser" value
    Then I fill in "user_form_username" with "justForTestUser13"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate13@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate13@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I uncheck "Admin"
        And I uncheck "Instructor"
        And I uncheck "instructorStatement"
        And I uncheck "Student"
        And I uncheck "studentStatement"
        And I uncheck "Proctor"
        And I uncheck "proctorStatement"
        And I uncheck "Training Manager"
        And I uncheck "trainingManagerStatement"
        And I uncheck "Test Center Administrator"
        And I uncheck "testCenterAdministratorStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/users"

Scenario: admin edit user with invalid fields
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "tmuser" value
    Then I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyy"
        And I fill in "email" with "justfortestuser_certigate@gmail.com"
        And I fill in "confirmEmail" with "yyyy"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Edit"
        And I should be on "/users/edit/3"
        And I should see "This username is already in use"
        And I should see "This email address is already in use"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long" 2 times
        And I should see "File has an incorrect extension"
        And I should see text matching "Please enter valid (phone|mobile) number" 2 times
        And I should see "The input does not appear to be a valid date" 4 times

Scenario: admin edit user with failed confirmation fields
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "tmuser" value
    Then I fill in "user_form_username" with "justForTestUser"
        And I fill in "user_form_password" with "xxxx"
        And I fill in "confirmPassword" with "yyyyyyyyyyyy"
        And I fill in "email" with "justfortestuser_certigate"
        And I fill in "confirmEmail" with "justfortestuser_certigate@gmail.com"
        And I fill in "firstName" with ""
        And I fill in "firstNameAr" with ""
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with ""
        And I fill in "lastNameAr" with ""
        And I fill in "mobile" with "0111011101110111"
        And I fill in "phone" with "0111011101110111"
        And I fill in "addressOne" with ""
        And I fill in "addressOneAr" with ""
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with ""
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with ""
        And I fill in "securityQuestion" with ""
        And I fill in "securityAnswer" with ""
        And I fill in "identificationNumber" with ""
        And I fill in "identificationExpiryDate" with "date"
        And I fill in "identificationExpiryDateHj" with "date"
        And I fill in "dateOfBirth" with "date"
        And I fill in "dateOfBirthHj" with "date"
        And I fill hidden field "longitude" with ""
        And I fill hidden field "latitude" with ""
        And I attach the file "text.pdf" to "photo"
    Then I press "Edit"
        And I should be on "/users/edit/3"
        And I should see "The input is not a valid email address."
        And I should see "The input is less than 8 characters long"
        And I should see "password doesnt match"
        And I should see "email doesnt match"

Scenario: admin edit user with random type without agreement
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "tmuser" value
    Then I fill in "user_form_username" with "justForTestUser14"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate14@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate14@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I uncheck "Admin"
        And I uncheck "Instructor"
        And I uncheck "instructorStatement"
        And I check "Student"
        And I uncheck "studentStatement"
        And I uncheck "Proctor"
        And I uncheck "proctorStatement"
        And I uncheck "Training Manager"
        And I uncheck "trainingManagerStatement"
        And I uncheck "Test Center Administrator"
        And I uncheck "testCenterAdministratorStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/users"

Scenario: admin edit user with random type with agreement
    Given I mock the login session
        And I am on "/users"
        And I perform "Edit" action on row with "instructor" value
    Then I fill in "user_form_username" with "justForTestUser15"
        And I fill in "user_form_password" with ""
        And I fill in "confirmPassword" with ""
        And I fill in "email" with "justfortestuser_certigate15@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate15@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I uncheck "Admin"
        And I uncheck "Instructor"
        And I uncheck "instructorStatement"
        And I check "Student"
        And I check "studentStatement"
        And I uncheck "Proctor"
        And I uncheck "proctorStatement"
        And I uncheck "Training Manager"
        And I uncheck "trainingManagerStatement"
        And I uncheck "Test Center Administrator"
        And I uncheck "testCenterAdministratorStatement"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Edit"
        And I should be on "/users"

Scenario: admin register new user with random type without autologin
    Given I mock the login session
        And I am on "/users/new"
        And I should see 1 "input[name='username']" elements
        And I should see 2 "label:contains('Admin')" elements
        And I fill in "user_form_username" with "justForTestUser16"
        And I fill in "user_form_password" with "veryStrongP@$$w0rd"
        And I fill in "confirmPassword" with "veryStrongP@$$w0rd"
        And I fill in "email" with "justfortestuser_certigate16@gmail.com"
        And I fill in "confirmEmail" with "justfortestuser_certigate16@gmail.com"
        And I fill in "firstName" with "User"
        And I fill in "firstNameAr" with "User"
        And I fill in "middleName" with "User"
        And I fill in "middleNameAr" with "User"
        And I fill in "lastName" with "User"
        And I fill in "lastNameAr" with "User"
        And I fill in "mobile" with "0111599198"
        And I fill in "phone" with "0111599198"
        And I fill in "addressOne" with "street one"
        And I fill in "addressOneAr" with "street one"
        And I fill in "addressTwo" with "street two"
        And I fill in "addressTwoAr" with "street two"
        And I fill in "city" with "cairo"
        And I fill in "zipCode" with "11111"
        And I fill in "identificationType" with "licence"
        And I fill in "securityQuestion" with "licence"
        And I fill in "securityAnswer" with "i do not have any"
        And I fill in "identificationNumber" with "11111"
        And I fill in "identificationExpiryDate" with "15/02/2020"
        And I fill in "identificationExpiryDateHj" with "21/06/1441"
        And I fill in "dateOfBirth" with "15/02/1980"
        And I fill in "dateOfBirthHj" with "21/06/1401"
        And I fill hidden field "longitude" with "31.23571160000006"
        And I fill hidden field "latitude" with "30.0444196"
        And I check "privacyStatement"
        And I check "instructorStatement"
        And I check "studentStatement"
        And I check "trainingManagerStatement"
        And I check "testCenterAdministratorStatement"
        And I check "proctorStatement"
        And I check "Test Center Administrator"
        And I check "Training Manager"
        And I check "Instructor"
        And I check "Student"
        And I check "Proctor"
        And I select "Egypt" from "country"
        And I select "Egypt" from "nationality"
        And I select "Arabic" from "language"
        And I attach the file "user.png" to "photo"
    Then I press "Create"
        And I should be on "/users"
        And I should see 0 "input[name='username']" elements
        And I should see 0 "input[name='password']" elements
        And I should see "admin"

Scenario: admin can not delete himself/herself
    Given I mock the login session
        And I am on "/users"
        And I perform "Delete" action on row with "admin" value
    Then I should be on "/noaccess"

Scenario: admin can not activate himself/herself
    Given I mock the login session
        And I am on "/users"
        And I perform "Activate" action on row with "admin" value
    Then I should be on "/noaccess"