{{% BLOCKS }}
{{<layout}}
{{$content}}
<br />
<a href="/organizations/new?organization=1"><button class="btn btn-small btn-success create-new">Create new ATC</button></a>
<br/>
<div class="panel panel-default atcs-list">
    <div class="panel-heading">ATCs</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Commercial Name</th>
                <th>City</th>
                <th>Phone</th>
                <th>WebSite</th>
                <th>ATC License Expiration</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#userList}}
            <tr>
                <td>{{commercialName}}</td>
                <td>{{city}}</td>
                <td>{{phone1}}</td>
                <td>{{website}}</td>
                <td>{{atcLicenseExpiration}}</td>
                <td>
                    <a href="/organizations/more/{{id}}">More</a>     
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a data-toggle="tooltip" data-placement="left" title="Edit" href="/organizations/edit/{{id}}?organization=1"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{#active}}
                    <a data-toggle="tooltip" data-placement="left" title="Delete" href="/organizations/delete/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/active}}
                </td>
            </tr>
            {{/userList}}
        </tbody>
    </table>
</div>

{{/content}}

{{/layout}}
