{{% BLOCKS }}
{{<layout}}
{{$content}}
{{#userData}}
<hr>
<div class="container">
    <div class="row">
        <div class="col-sm-6"><h1>{{commercialName}}</h1></div>
    </div>
    <div class="row">
        <div class="col-sm-3">

            <ul class="list-group">
                <li class="list-group-item text-muted">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Commercial Name</strong></span>{{commercialName}}</li>
            </ul> 

            <ul class="list-group">
                <li class="list-group-item text-muted">Owner Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Owner</strong></span>{{ownerName}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Owner National Id</strong></span>{{ownerNationalId}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>CR No.</strong></span>{{CRNo}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>CR Expiration Date</strong></span>{{CRExpiration}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>CR</strong></span><a href="/">show</a></li>
            </ul> 

            <ul class="list-group">
                <li class="list-group-item text-muted">Contacts</li>

                <li class="list-group-item text-right"><span class="pull-left"><strong>Phone</strong></span>{{phone1}}</li>
                {{#phone2}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>Phone</strong></span>{{phone2}}</li>
                {{/phone2}}
                {{#phone3}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>Phone</strong></span>{{phone3}}</li>
                {{/phone3}}
                {{#fax}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>Fax</strong></span>{{fax}}</li>
                {{/fax}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>Email</strong></span> {{email}}</li>
            </ul> 
        </div>
    </div>
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">Find Us</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Address</strong></span>{{addressLine1}}</li>
                {{#addressLine2}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>Address</strong></span>{{addressLine1}}</li>
                {{/addressLine2}}
                <li class="list-group-item text-right"><span class="pull-left"><strong>City</strong></span>{{city}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ZipCode</strong></span>{{zipCode}}</li>

            </ul>
        </div>
    </div>

    
    {{#atpLicenseNo}}
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">ATP Info.</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATP License No.</strong></span>{{atpLicenseNo}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATP License Expiration Date</strong></span>{{atpLicenseExpiration}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATP License</strong></span><a href="/">show</a></li>
            </ul>
        </div>
    </div>
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">ATP Resources</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Labs No.</strong></span>{{labsNo}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Pcs/Lab</strong></span>{{pcsNo_lab}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>OS</strong></span>{{operatingSystem}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>OS Language</strong></span>{{operatingSystemLang}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Microsoft Office Version</strong></span>{{officeVersion}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Microsoft Office Language</strong></span>{{officeLang}}</li>
            </ul>
        </div>
    </div>
    {{/atpLicenseNo}}


    {{#atcLicenseNo}}
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">ATC Info.</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATC License No.</strong></span>{{atcLicenseNo}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATC License Expiration Date</strong></span>{{atcLicenseExpiration}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>ATC License</strong></span><a href="/">show</a></li>
            </ul>
        </div>
    </div>
    
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">ATC Resources</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Classes No.</strong></span>{{labsNo}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Pcs/Class</strong></span>{{pcsNo_lab}}</li>
            </ul>
        </div>
    </div>
    
    {{/atcLicenseNo}}
















    {{/userData}}

    {{/content}}

    {{/layout}}
