{{% BLOCKS }}
{{<layout}}
{{$content}}

<div class="panel panel-default">
    <div class="panel-body">
        <form id="orgReg" class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            <fieldset>

                <!-- Form Name -->
                <legend>New Organization</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="commercialName">Commercial Name</label>  
                    <div class="col-md-4">
                        <input id="commercialName" name="commercialName" type="text" placeholder="Commercial Name" class="form-control input-md" required="
                               ">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="long">Longitude </label>  
                    <div class="col-md-4">
                        <input id="long" name="long" type="text" placeholder="" class="form-control input-md">
                        <span class="help-block">please find yourself on the map</span>  
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="lat">Latitude</label>  
                    <div class="col-md-4">
                        <input id="lat" name="lat" type="text" placeholder="" class="form-control input-md">
                        <span class="help-block">please find yourself on the map</span>  
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="ownerName">Owner Name</label>  
                    <div class="col-md-4">
                        <input id="ownerName" name="ownerName" type="text" placeholder="Owner Name" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="ownerNationalId">Owner National Id</label>  
                    <div class="col-md-4">
                        <input id="ownerNationalId" name="ownerNationalId" type="text" placeholder="Owner National Id" class="form-control input-md" required="true
                               ">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="CRNo">CR No.</label>  
                    <div class="col-md-4">
                        <input id="CRNo" name="CRNo" type="text" placeholder="CR No." class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="CRExpiration">CR Expiration Date</label>  
                    <div class="col-md-4">
                        <input id="CRExpiration" name="CRExpiration" type="text" placeholder="CR Expiration Date" class="form-control input-md datepicker" required="required">

                    </div>
                </div>

                <!-- File Button --> 
                <div class="form-group">
                    <label class="col-md-4 control-label" for="CRAttachment">CR Attachment</label>
                    <div class="col-md-4">
                        <input id="CRAttachment" name="CRAttachment" class="input-file" type="file">
                    </div>
                </div>

                <!-- Multiple Radios (inline) -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="type">Organization Type</label>
                    <div class="col-md-4"> 
                        <label class="radio-inline" for="type-0">
                            <input type="checkbox" class="type" name="type" id="type-0" value="1">
                            ATC
                        </label> 
                        <label class="radio-inline" for="type-1">
                            <input type="checkbox" class="type"name="type" id="type-1" value="2">
                            ATP
                        </label> 
                    </div>
                </div>

                <!-- Hidden text input-->
                <div class="form-group">
                    <div class="col-md-4">
                        <input id="hiddenType" name="type" type="hidden" class="form-control input-md">

                    </div>
                </div>

                <div id="atpSet">
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atpLicenseNo">ATP License Number</label>  
                        <div class="col-md-4">
                            <input id="atpLicenseNo" name="atpLicenseNo" type="text" placeholder="LicenseATP License Number" class="form-control input-md">

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atpLicenseExpiration">ATP License Expiration Date</label>  
                        <div class="col-md-4">
                            <input id="atpLicenseExpiration" name="atpLicenseExpiration" type="text" placeholder="ATP License Expiration Date" class="datepicker form-control input-md">

                        </div>
                    </div>

                    <!-- File Button --> 
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atpLicenseAttachment">ATP License Attachment</label>
                        <div class="col-md-4">
                            <input id="atpLicenseAttachment" name="atpLicenseAttachment" class="input-file" type="file">
                        </div>
                    </div>




                    <div id="atp_resource">
                        <!-- Text input-->
                        <div class="form-group">
                            <label class=" col-md-4 control-label" for="labsNo">Labs No</label>  
                            <div class="col-md-4">
                                <input id="labsNo" name="labsNo" type="text" placeholder="Labs No" class=" form-control input-md" required="false">

                            </div>
                        </div>



                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="pcsNo_lab">PCs / Lab</label>  
                            <div class="col-md-4">
                                <input id="pcsNo_lab" name="pcsNo_lab" type="text" placeholder="PCs / Lab" class=" form-control input-md" required="false">

                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class=" col-md-4 control-label" for="internetSpeed_lab">Internet Speed / L</label>  
                            <div class="col-md-4">
                                <input id="internetSpeed_lab" name="internetSpeed_lab" type="text" placeholder="InternetSpeed / L" class=" form-control input-md" required="false">

                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class=" col-md-4 control-label" for="operatingSystem">Operating System</label>  
                            <div class="col-md-4">
                                <input id="operatingSystem" name="operatingSystem" type="text" placeholder="Operating System" class=" form-control input-md" required="false">

                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class=" col-md-4 control-label" for="operatingSystemLang">Operating System Language</label>  
                            <div class="col-md-4">
                                <input id="operatingSystemLang" name="operatingSystemLang" type="text" placeholder="Operating System Language" class=" form-control input-md" required="false">

                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class=" col-md-4 control-label" for="officeVersion">Microsoft Office Version</label>  
                            <div class="col-md-4">
                                <input id="officeVersion" name="officeVersion" type="text" placeholder="Microsoft Office Version" class=" form-control input-md" required="false">

                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="atp_resource col-md-4 control-label" for="officeLang">Microsoft Office Language</label>  
                            <div class="col-md-4">
                                <input id="officeLang" name="officeLang" type="text" placeholder="Microsoft Office Language" class=" form-control input-md" required="false">

                            </div>
                        </div>
                    </div>

                </div>
                
                <hr>
                <!-- Text input-->
                <div id="atcSet">
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atcLicenseNo">ATC License Number</label>  
                        <div class="col-md-4">
                            <input id="atcLicenseNo" name="atcLicenseNo" type="text" placeholder="ATC License Number" class="form-control input-md">

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atcLicenseExpiration">ATC License Expiration Date</label>  
                        <div class="col-md-4">
                            <input id="atcLicenseExpiration" name="atcLicenseExpiration" type="text" placeholder="ATC License Expiration Date" class="datepicker form-control input-md">

                        </div>
                    </div>

                    <!-- File Button --> 
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="atcLicenseAttachment">ATC License Attachment</label>
                        <div class="col-md-4">
                            <input id="atcLicenseAttachment" name="atcLicenseAttachment" class="input-file" type="file">
                        </div>
                    </div>


                    <!-- Text input-->
                    <div class="form-group">
                        <label class=" col-md-4 control-label" for="classesNo">Classes No.</label>  
                        <div class="col-md-4">
                            <input id="classesNo" name="classesNo" type="text" placeholder="Classes No." class=" form-control input-md" required="false">

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class=" col-md-4 control-label" for="pcsNo_class">PCs / Class </label>  
                        <div class="col-md-4">
                            <input id="pcsNo_class" name="pcsNo_class" type="text" placeholder="PCs / Class " class=" form-control input-md" required="false">

                        </div>
                    </div>

                </div>
                
                <hr>
                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="addressline1">Address 1</label>  
                    <div class="col-md-4">
                        <input id="addressLine1" name="addressLine1" type="text" placeholder="Address 1" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="addressLine2">Address 2</label>  
                    <div class="col-md-4">
                        <input id="addressLine2" name="addressLine2" type="text" placeholder="Address 2" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="city">City</label>  
                    <div class="col-md-4">
                        <input id="city" name="city" type="text" placeholder="City" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="zipCode">ZipCode</label>  
                    <div class="col-md-4">
                        <input id="zipCode" name="zipCode" type="text" placeholder="ZipCode" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="phone1">Phone 1</label>  
                    <div class="col-md-4">
                        <input id="phone1" name="phone1" type="text" placeholder="Phone 1" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="phone2">Phone 2</label>  
                    <div class="col-md-4">
                        <input id="phone2" name="phone2" type="text" placeholder="Phone 2" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="phone3">Phone 3</label>  
                    <div class="col-md-4">
                        <input id="phone3" name="phone3" type="text" placeholder="Phone 3" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="fax">Fax</label>  
                    <div class="col-md-4">
                        <input id="fax" name="fax" type="text" placeholder="Fax" class="form-control input-md">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="website">Website</label>  
                    <div class="col-md-4">
                        <input id="website" name="website" type="text" placeholder="Website" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="email">Official Email</label>  
                    <div class="col-md-4">
                        <input id="email" name="email" type="text" placeholder="Official Email" class="form-control input-md" required="required">

                    </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="trainingManager">Training Manager</label>
                    <div class="col-md-4">
                        <select id="trainingManager" name="trainingManager_id" class="form-control">
                            <option value="0">__Select__</option>
                            {{#userList}}
                            <option value="{{id}}">{{firstName}} {{middleName}} {{lastName}}</option>
                            {{/userList}}
                        </select>
                    </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="testCenterAdmin">Test Center Admin</label>
                    <div class="col-md-4">
                        <select id="trainingManager" name="testCenterAdmin_id" class="form-control">
                            <option value="0">__Select__</option>
                            {{#userList}}
                            <option value="{{id}}">{{firstName}} {{middleName}} {{lastName}}</option>
                            {{/userList}}
                        </select>
                    </div>
                </div>

                <!-- Select Basic -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="focalContactPerson">Focal Contact Person</label>
                    <div class="col-md-4">
                        <select id="focalContactPerson" name="focalContactPerson_id" class="form-control" required="required">
                            <option value="0">__Select__</option>
                            {{#userList}}
                            <option value="{{id}}">{{firstName}} {{middleName}} {{lastName}}</option>
                            {{/userList}}
                        </select>
                    </div>
                </div>




            </fieldset>
            <!-- Button (Double) -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="submit"></label>
                <div class="col-md-8">
                    <a data-toggle="modal" href="#agreementModal" class="btn btn-success">Submit</a>
                    <button id="reset" type="reset" name="reset" class="btn btn-danger">Reset</button>
                </div>
            </div>    
        </form>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="agreementModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Agreement</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button"  name="submit" id="submit" class="btn btn-primary">Save Organization</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<script src="/concat/app.js" type="text/javascript"></script>
{{/content}}

{{/layout}}
