{{% BLOCKS }}
{{<layout}}
{{$content}}
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translation}}Courses Outlines{{/translation}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translation}}Title{{/translation}}</th>
                <th>{{#translation}}Duration{{/translation}}</th>
            </tr>
        </thead>
        <tbody>
            {{#outlines}}
            <tr>
                <td>{{title}}</td>
                <td>{{duration}} {{#translation}}mins{{/translation}}</td>
            </tr>
            {{/outlines}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
