{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/course-events/new{{#courseId}}/{{courseId}}{{/courseId}}"><button class="btn btn-small btn-success">Create new Course Event</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translation}}Course Events{{/translation}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translation}}Name{{/translation}}</th>
                <th>{{#translation}}Start Date{{/translation}}</th>
                <th>{{#translation}}End Date{{/translation}}</th>
                <th>{{#translation}}Instructor{{/translation}}</th>
                <th>{{#translation}}ATP{{/translation}}</th>
                <th>{{#translation}}Status{{/translation}}</th>
                <th colspan="2">{{#translation}}Actions{{/translation}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courseEvents}}
            <tr class="{{^status}}container-inactive{{/status}}">
                <td>{{course.name}}</td>
                <td>{{startDate}}</td>
                <td>{{endDate}}</td>
                <td>{{ai.firstName}} {{ai.lastName}}</td>
                <td>{{atp.commercialName}}</td>
                <td>{{statusText}}</td>
                <td>
                    <a href="/course-events/edit/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" data-toggle="tooltip" data-placement="left" title="{{#translation}}Edit{{/translation}}"><span class="glyphicon glyphicon-edit"></span></a>
                    {{#status}}
                    &nbsp;&nbsp;&nbsp;
                    <a href="/course-events/delete/{{id}}{{#courseId}}/{{courseId}}{{/courseId}}" data-toggle="tooltip" data-placement="left" title="{{#translation}}Delete{{/translation}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/status}}
                </td>
            </tr>
            {{/courseEvents}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
