{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/courses/evaluation/new/{{courseId}}"><button class="btn btn-small btn-success">Create new Evaluation</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Default Evaluation Templates</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Question Title</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#questions}}
            <tr>
                <td>{{questionTitle}}</td>
                <td>
                    <a href="/courses/evaluation/edit/{{courseId}}/{{id}}" data-toggle="tooltip" data-placement="left" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/courses/evaluation/delete/{{courseId}}/{{id}}" data-toggle="tooltip" data-placement="left" title="Delete"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
            {{/questions}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
