{{% BLOCKS }}
{{<layout}}
{{$content}}

{{{orgForm}}}

<script src="/concat/app.js" type="text/javascript"></script>
<script>
$(document).ready(function () {

    $orgType = getParameterByName('t');
    switch ($orgType) {
        case '1' :
            $('#org_form_type').val("1");
            break;
        case '2' :
            $('#org_form_type').val("2");
            break;
        case '3' :
            $('#org_form_type').val("3");
            break;
        default:
            //for hacking
//            window.location.replace("/sign/out");
            break;
    }


























    function getParameterByName(name) {
        name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                results = regex.exec(location.search);
        return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
    }
});
</script>
{{/content}}

{{/layout}}
