<!--{{% BLOCKS }}
{{<layout}}
hide header
{{$headerContainer}}
{{/headerContainer}}
hide footer
{{$footerContainer}}
{{/footerContainer}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{#translate}}Course Outlines{{/translate}}</h3>
    </div>
    <div class="panel-body">

        <table class="table">
            <thead>
                {{#outlines.count}}
                <tr>
                    <th>{{#translate}}Title{{/translate}}</th>
                    <th>{{#translate}}Duration{{/translate}} ({{#translate}}minutes{{/translate}})</th>
                </tr>
                {{/outlines.count}}
            </thead>
            <tbody>
                {{#outlines}}
                {{#statusActive}}
                <tr>
                    <td>{{title}}</td>
                    <td>{{duration}}</td>
                </tr>
                {{/statusActive}}
                {{/outlines}} 
            </tbody>
        </table>
    </div>
</div>
{{/content}}
{{/layout}}-->

<html>
    <head>

    </head>
    <body>
        <h1>Course Outlines</h1>
        <table class="table">
            <tr>
                <th>Outline Title</th>
                <th>Duration in minutes</th>
            </tr>
            <?php foreach ($this->outlines as $outline) { ?>
                <?php if ($outline->getStatus()) : ?>
                    <tr>
                        <td>
                            <?php echo $outline->getTitle(); ?>
                        </td>
                        <td>
                            <?php echo $outline->getDuration(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php } ?>
        </table>

    </body>

</html>