{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/organization-users/new/{{organizationId}}"><button class="btn btn-small btn-success">{{#translate}}Add new Organization User{{/translate}}</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Organization Users{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}User{{/translate}}</th>
                <th>{{#translate}}Role{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#organizationUsers}}
            <tr>
                <td>
                    {{#locale_en}}
                    {{user.firstName}}{{#user.middleName}} {{user.middleName}}{{/user.middleName}} {{user.lastName}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{user.firstNameAr}}{{#user.middleNameAr}} {{user.middleNameAr}}{{/user.middleNameAr}} {{user.lastNameAr}}
                    {{/locale_ar}}
                </td>
                <td>
                    {{#locale_en}}
                    {{role.name}}
                    {{/locale_en}}
                    {{#locale_ar}}
                    {{role.nameAr}}
                    {{/locale_ar}}        
                </td>
                <td>
                    {{^isCurrentUser}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="/organization-users/delete/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Delete{{/translate}}"><span class="glyphicon glyphicon-remove"></span></a>
                    {{/isCurrentUser}}
                </td>
            </tr>
            {{/organizationUsers}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
