{{% BLOCKS }}
{{<layout}}
{{$content}}
<br>
<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Courses Calendar{{/translate}}</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Course name{{/translate}}</th>
                <th>{{#translate}}Start Date{{/translate}}</th>
                <th>{{#translate}}End Date{{/translate}}</th>
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courses}}
            <tr>
                <td>{{name}}</td>
                <td>{{startDate}}</td>
                <td>{{endDate}}</td>
                <td>
                    <a href="/courses/more/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}More{{/translate}}"><span class="glyphicon glyphicon-expand"></span></a>
                    {{#canEnroll}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/courses/enroll/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Enroll{{/translate}}"><span class="glyphicon glyphicon-plus"></span></a>
                    {{/canEnroll}}
                    {{#canLeave}}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="/courses/leave/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Leave{{/translate}}"><span class="glyphicon glyphicon-minus"></span></a>
                    {{/canLeave}}
                </td>
            </tr>
            {{/courses}}
            </td>
            </tr>
        </tbody>
    </table>
</div>
{{/content}}
{{/layout}}
