{{% BLOCKS }}
{{<layout}}

{{$content}}
<ul>    
    {{#validationError}}
    <li>{{.}}</li>
    {{/validationError}}
</ul>
<form id="editForm" class="form-horizontal" method="POST" action="">
    <fieldset>

        <!-- Form Name -->
        <legend>{{#translate}}Evaluation Template{{/translate}}</legend>
        {{#questions}}
        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="editedQuestion[]">{{#translate}}Question Title{{/translate}}</label>  
            <div class=" col-md-4">
                <input name="editedQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control editedInputs input-md" required=""value="{{questionTitle}}">
                <a href="#" class="deleteQuestion removeQ" >X</a>
                <input type="hidden" class="dummy" name="original[]" value="{{questionTitle}}"/>
            </div>
        </div>
        {{/questions}}
        {{#unvalidQuestions}}
        <div class="form-group" >
            <label class="col-md-4 error control-label" for="newQuestion[]">{{#translate}}Question Title{{/translate}}</label>  
            <div class=" col-md-4">
                <input name="newQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required=""value="{{.}}">
                <a href="#" class="deleteInvalidQuestion removeQ" >X</a>
            </div>
        </div>
        {{/unvalidQuestions}}

        <span id="endOfText"></span>
        <!-- button -->
        <div class=" row form-group">
            <div class="col-md-4">
                <button id="singlebutton" name="submit" class="btn btn-success">{{#translate}}Edit Evaluation Template{{/translate}}</button>
            </div>
        </div>

    </fieldset>
</form>

<button type="button" id="addmore" class=" btn btn-primary">{{#translate}}Add More{{/translate}}</button>


<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>
$(document).ready(function () {
    //
    numerateLabels();

    $('#addmore').click(function () {
        getMeNewInput();
    });

    function getMeNewInput() {
        window.template = '<div class="form-group"> <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label> <div class="col-md-4"> <input name="newQuestion[]" type="text" placeholder="Add Your Question Here" class="questionInputs form-control input-md" required=""> <a href="#" class="deleteNewQuestion removeQ">X</a></div></div>';
        $('#endOfText').before(window.template);
        numerateLabels();

    }

    function numerateLabels() {
        window.index = 1
        $('.control-label').each(function () {
            if ($(this).parent().is(":visible")) {
                $(this).text('Question Title ' + window.index)
                window.index++;
            }
        });
    }

    /**
     * This action is meant to delete 
     */
    $('.deleteQuestion').click(function () {
        // remove questionInputs class and replace it with deletedQuestion class
        $(this).prev().attr("class", "deletedquestion form-control input-md");
        // change input name 
        $(this).prev().prop("name", 'deleted[]');
        // hide deleted input
        $(this).parent().parent().hide();
        //remove original value no longer needed
        $(this).next().remove();
        numerateLabels();
    });
    
    // to delete run time created questions  
    $(document).on("click", ".deleteNewQuestion", function () {
        $(this).parent().parent().remove();
        numerateLabels();
    });

    $('.deleteInvalidQuestion').click(function () {
        //delete input
        $(this).parent().parent().remove();
        numerateLabels();

    });

});

</script>


{{/content}}

{{/layout}}