{{% BLOCKS }}
{{<layout}}

{{$content}}
<ul>    
    {{#validationError}}
    <li class="error">{{.}}</li>
    {{/validationError}}
</ul>
<form id="editForm" class="form-horizontal" method="POST" action="">
    <fieldset>

        <!-- Form Name -->
        <legend>{{#translate}}Evaluation Template{{/translate}}</legend>
        {{#questions}}
        <div class="form-group" >
            <div class="questionContainer row">
                <label class="col-md-4 control-label englishLabel">{{#translate}}Question Title{{/translate}}</label>  
                <div class="col-md-4">
                    <input name="editedQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required="" value="{{questionTitle}}">
                    <a href="#" class="deleteQuestion removeQ pull-left" >X</a>
                    <input type="hidden" class="dummy" name="original[]" value="{{questionTitle}}"/>
                </div>
                <div class="col-md-4">

                </div>
            </div>

            <div class="questionContainer row">
                <label class="col-md-4 control-label">{{#translate}}Question Title in Arabic{{/translate}}</label>  
                <div class="col-md-4">
                    <input name="editedQuestionAr[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required="" value="{{questionTitleAr}}">
                    <input type="hidden" class="dummy" name="originalAr[]" value="{{questionTitleAr}}"/>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
        {{/questions}}

        <span id="endOfText"></span>
        <!-- button -->
        <div class=" row form-group">
            <div class="col-md-4">
                <button id="singlebutton" name="submit" class="btn btn-success">{{#translate}}Edit Evaluation Template{{/translate}}</button>
            </div>
        </div>

    </fieldset>
</form>

<button type="button" id="addmore" class=" btn btn-primary">{{#translate}}Add More{{/translate}}</button>

{{/content}}

{{/layout}}
<script>
    $(document).ready(function () {
        //
        numerateLabels();

        $('#addmore').click(function () {
            getMeNewInput();
        });

        function getMeNewInput() {
//        window.template = '<div class="form-group"> <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label> <div class="col-md-4"> <input name="newQuestion[]" type="text" placeholder="Add Your Question Here" class="questionInputs form-control input-md" required=""> <a href="#" class="deleteNewQuestion removeQ">X</a></div></div>';
            window.template = '<div class="form-group" > <div class="questionContainer row"> <label class="col-md-4 control-label englishLabel" for="newQuestion[]">{{#translate}}Question Title{{/translate}}</label> <div class="col-md-4"> <input name="newQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required=""> <a href="#" class="deleteNewQuestion removeQ pull-left" >X</a> </div> </div> <div class="questionContainer row"> <label class="col-md-4 control-label" for="newQuestionAr[]">{{#translate}}Question Title in Arabic{{/translate}}</label> <div class="col-md-4"> <input name="newQuestionAr[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required=""> </div> </div> </div>';
            $('#endOfText').before(window.template);
            numerateLabels();

        }

        function numerateLabels() {
            window.index = 1
            $('.englishLabel').each(function () {
                if ($(this).parent().is(":visible")) {
                    $(this).text('Question Title ' + window.index)
                    window.index++;
                }
            });
        }

        /**
         * This action is meant to delete 
         */
        $('.deleteQuestion').click(function () {
            // remove questionInputs class and replace it with deletedQuestion class
            $(this).prev().attr("class", "deletedquestion form-control input-md");
            // change english input name 
            $(this).prev().prop("name", 'deleted[]');
            // change arabic input name 
            $(this).parents('.form-group').find('.questionInputs').prop("name", 'deletedAr[]');
            // hide deleted input
            $(this).parent().parent().parent().hide();
            //remove original value no longer needed
            $(this).parents('.form-group').find('.dummy').remove();
            numerateLabels();
        });

        // to delete run time created questions  
        $(document).on("click", ".deleteNewQuestion", function () {
            $(this).parent().parent().parent().remove();
            numerateLabels();
        });

        $('.deleteInvalidQuestion').click(function () {
            //delete input
            $(this).parent().parent().remove();
            numerateLabels();

        });

    });

</script>

