{{% BLOCKS }}
{{<layout}}

{{$content}}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#courseDetails" aria-controls="courseDetails" role="tab" data-toggle="tab">{{#translate}}Course Details{{/translate}}</a></li>
    <li role="presentation"><a href="/courses/evaluation/edit/{{courseId}}" aria-controls="courseEvaluation">{{#translate}}Course Evaluation{{/translate}}</a></li>
    <li role="presentation"><a href="/courses/resources/edit/{{courseId}}" aria-controls="courseResources">{{#translate}}Course Resources{{/translate}}</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="courseDetails">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{#translate}}Edit Course{{/translate}}</h3>
            </div>
            <div class="panel-body">
                {{{courseForm}}}
            </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="courseEvaluation">...</div>
    <div role="tabpanel" class="tab-pane" id="courseResources">...</div>
</div>
{{/content}}

{{$scripts}}
<script>
    $(document).ready(function () {
    updateOutlines("#course_form_addMore", {{#isAdminUser}}true{{/isAdminUser}}{{^isAdminUser}}false{{/isAdminUser}})
    });
</script>
{{/scripts}}
{{/layout}}
