{{% BLOCKS }}
{{<layout}}
{{$content}}

<br><br>
<h4 class="h4">{{#translate}}Course You Are Assigned To{{/translate}} ..</h4>

<div class="panel panel-default">

    <table class="table">
        <thead>
            <tr>
                <th>{{#translate}}Course name{{/translate}}</th>
                <th>{{#translate}}Brief{{/translate}}</th>
                <th>{{#translate}}Start Date{{/translate}}</th>
                <th>{{#translate}}End Date{{/translate}}</th>
                <th>{{#translate}}Duration{{/translate}} ({{#translate}}Days{{/translate}})</th>
                <th>{{#translate}}Authorized Training Partner{{/translate}}</th>
                <th>{{#translate}}Rating{{/translate}}</th>
                
                <th colspan="2">{{#translate}}Actions{{/translate}}</th>
            </tr>
        </thead>
        <tbody>
            {{#courses}}
            <tr>
                <td>
                    {{name}}
                </td>

                <td>
                    {{brief}}
                </td>
                <td>
                    {{startDate}}
                </td>
                <td>
                    {{endDate}}
                </td>
                <td>
                    {{duration}} {{#translate}}Days{{/translate}}
                </td>
                <td>
                    {{atp.commercialName}}
                </td>
                <td>
                    {{evaluation.percentage}} %
                </td>
                <td>
                    <a href="/courses/more/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}More{{/translate}}"><span class="glyphicon glyphicon-folder-close"></span></a>
                    &nbsp;
                    <a href="/resources/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Resources{{/translate}}"><span class="glyphicon glyphicon glyphicon-film"></span></a>
                    &nbsp;
                    <a href="/courses/outlines/{{id}}" data-toggle="tooltip" data-placement="left" title="{{#translate}}Outlines{{/translate}}"><span class=" glyphicon glyphicon-list-alt"></span></a>
                </td>
            </tr>



            {{/courses}}
        </tbody>
    </table>
    {{/content}}
    {{/layout}}
