{{% BLOCKS }}
{{<layout}}
{{$content}}
<a href="/courses/calendar"><button class="btn btn-small btn-success"><span class="glyphicon glyphicon-arrow-left"></span></button></a>
<br><br>

<br><br>
<!--make sure that user did not evaluated the course before-->
{{#notEvaluatedBefore}}
<!--making sure that course has evaluation-->
{{#hasEvaluation}}
<!--making sure that user is student-->
{{#isStudent}}
<!--this rule is only for students-->
<a class="btn btn-info" href="/courses/vote/{{course.id}}" >{{#translate}}Evaluate Course{{/translate}}</a>
<br><br>
{{/isStudent}}
{{/hasEvaluation}}
{{/notEvaluatedBefore}}

<div class="panel panel-default">

    <div class="panel-heading">{{#translate}}Course Info{{/translate}}</div>

    <!-- Table -->

    {{#course}}
    <table class="table">
        <tbody>
            <tr>
                <td>{{#translate}}Name{{/translate}}</td>
                <td>{{name}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Brief{{/translate}}</td>
                <td>{{brief}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Authorized Instructor{{/translate}}</td>
                <td>{{ai.firstName}} {{ai.lastName}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Start Date{{/translate}}</td>
                <td>{{startDate}}</td>
            </tr>
            <tr>
                <td>{{#translate}}End Date{{/translate}}</td>
                <td>{{endDate}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Time{{/translate}}</td>
                <td>{{time}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Duration{{/translate}}</td>
                <td>{{duration}} {{#translate}}Day(s){{/translate}}</td>
            </tr>
            <tr>
                <td>{{#translate}}Authorized Training Partner{{/translate}}</td>
                <td>{{atp.commercialName}}</td>
            </tr>

            {{#outlines.count}}
            <td>{{#translate}}Outlines{{/translate}}</td><td></td>
            <tr>
                <td>&ensp; {{#translate}}Title{{/translate}}</td>
                <td>{{#translate}}Duration{{/translate}} ({{#translate}}minutes{{/translate}})</td>
            </tr>
            {{/outlines.count}}
            {{#outlines}}
                {{#statusActive}}
                <tr>
                    <td>&ensp; {{title}}</td>
                    <td>{{duration}}</td>
                </tr>
                {{/statusActive}}
            {{/outlines}} 

        {{#canDownloadResources}}

        {{#resources}}
        <td>Resources</td><td></td>
        {{/resources}}
        {{#resources}}
        <tr>
            <td>&ensp; {{type}}</td>
            <td>
                {{#files}}
                <a target="_blank" href="/resources/download/{{id}}" >{{name}}</a> <br>
                {{/files}}
            </td>
        </tr>
        {{/resources}} 
        {{/canDownloadResources}}
        </tbody>
    </table>
    {{/course}}

</div>
{{/content}}
{{/layout}}
