{{% BLOCKS }}
{{<layout}}

{{$content}}
<ul>    
    {{#validationError}}
    <li class="error">{{.}}</li>
    {{/validationError}}
</ul>
<form id="questions" class="form-horizontal" method="POST" action="">
    <fieldset>

        <!-- Form Name -->
        <legend>{{#translate}}Evaluation Template{{/translate}}</legend>
        {{#oldQuestions}}
        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="newQuestion[]">{{#translate}}Question Title{{/translate}}</label>  
            <div class=" col-md-4">
                <input name="newQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required=""value="{{.}}">
                <a href="#" class="deleteQuestion removeQ" >X</a>
            </div>
        </div>
        {{/oldQuestions}}
        <!-- Text input-->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="newQuestion[]">{{#translate}}Question Title{{/translate}}</label>  
            <div class="col-md-4">
                <input name="newQuestion[]" type="text" placeholder="{{#translate}}Add Your Question Here{{/translate}}" class="form-control questionInputs input-md" required="">
                <a href="#" class="deleteQuestion removeQ" >X</a>
            </div>
        </div>
        <span id="endOfText"></span>
        <!-- button -->
        <div class=" row form-group">
            <div class="col-md-4">
                <button id="singlebutton" name="submit" class="btn btn-success">{{#translate}}Submit Evaluation Template{{/translate}}</button>
            </div>
        </div>

    </fieldset>
</form>

<button type="button" id="addmore" class=" btn btn-primary">{{#translate}}Add More{{/translate}}</button>


<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>
$(document).ready(function () {
    window.index = 1;
    numerateLabels();

    $('#addmore').click(function () {
        getMeNewInput();
    });

    function getMeNewInput() {
        window.template = '<div class="form-group"> <label class="col-md-4 control-label" for="newQuestion[]">Question Title</label> <div class="col-md-4"> <input name="newQuestion[' + window.index + ']" type="text" placeholder="Add Your Question Here" class="form-control input-md" required=""> <a href="#" class="deleteQuestion removeQ" >X</a></div> </div>';
        $('#endOfText').before(window.template);
        numerateLabels();
    }

    function numerateLabels() {
        window.index = 1
        $('.control-label').each(function () {
            $(this).text('Question Title ' + window.index)
            window.index++;
        });
    }

    /**
     * This action is meant to delete 
     */
    $(document).on("click", ".deleteQuestion", function () {
//         delete template 
        $(this).parent().parent().remove();
        numerateLabels();
    });

});

</script>


{{/content}}

{{/layout}}