{{% BLOCKS }}
{{<layout}}
{{$content}}
<form  action="" method="POST" class="form-horizontal">
    <fieldset>

        <!-- Form Name -->
        <legend>{{#translate}}Course Evaluation{{/translate}}</legend>
        {{#questions}}
        <!-- Multiple Radios (inline) -->
        <div class="form-group" >
            <label class="col-md-4 control-label" for="radios">{{questionTitle}}</label>
            <div class="col-md-4"> 
                <label class="inline radio-inline" for="radios-0">
                    <input type="radio" name="radios_{{id}}" id="radios-0" value="1"  required="">
                    1
                </label> 
                <label class="inline radio-inline" for="radios-1">
                    <input type="radio" name="radios_{{id}}" id="radios-1" value="2">
                    2
                </label> 
                <label class="inline radio-inline" for="radios-2">
                    <input type="radio" name="radios_{{id}}" id="radios-2" value="3">
                    3
                </label> 
                <label class="inline radio-inline" for="radios-3">
                    <input type="radio" name="radios_{{id}}" id="radios-3" value="4">
                    4
                </label>
                <label class="inline radio-inline" for="radios-3">
                    <input type="radio" name="radios_{{id}}" id="radios-3" value="5">
                    5
                </label>
            </div>
        </div>
        {{/questions}}
        <center>
            <input type="submit"  name="submit" value="Save" />
        </center>
    </fieldset>

</form>
{{/content}}
{{/layout}}

