{{% BLOCKS }}
{{<layout}}

{{$content}}
<a href="/cms/page/history/{{id}}" data-toggle="tooltip" data-placement="left" title="View History"><button class="btn btn-small btn-success">View History</button></a>
<br><br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit Page</h3>
    </div>
    <div class="panel-body">
        {{{pageForm}}}
    </div>
</div>
{{/content}}
{{$scripts}}
<!--scripts can not be concatenated as other scripts/ style sheets are initiated with relative paths-->
<script type="text/javascript" src="/bower_components/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/pageCRUD.js"></script>
{{/scripts}}
{{/layout}}
