{{% BLOCKS }}
{{<layout}}
{{$content}}

<hr>
<div class="container">
    <div class="row">
        <div class="col-sm-6"><h1>{{name}}</h1></div>
    </div>
    <div class="row">
        <div class="col-sm-3">

<!--            <ul class="list-group">
                <li class="list-group-item text-muted">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span>{{name}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{joinDate}}</li>
            </ul> 

            <ul class="list-group">
                <li class="list-group-item text-muted">Contacts</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span>{{contanctName}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Website</strong></span> <a href="{{website}}">{{website}}</a></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Email</strong></span> {{email}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Address</strong></span> {{address}} ,{{city}}</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Telephone</strong></span> {{telephone}}</li>
            </ul> 
        </div>
    </div>
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">Description</li>
                <li class="list-group-item text-left">{{description}}</li>

            </ul>-->


<!--dummy data unhash pervious for implementation -->

            <ul class="list-group">
                <li class="list-group-item text-muted">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span>Test Atc</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> 15/5/2015</li>
            </ul> 

            <ul class="list-group">
                <li class="list-group-item text-muted">Contacts</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span>Mr.Atc</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Website</strong></span> <a href="www.Mr_atc.com">Mr_atc.com</a></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Email</strong></span> Mr_atc@atc.com</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Address</strong></span> Atc address</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Telephone</strong></span> +20000000000</li>
            </ul> 
        </div>
    </div>
    <div class="row" >
        <div class="col-sm-6">
            <ul class="list-group">
                <li class="list-group-item text-muted">Description</li>
                <li class="list-group-item text-left">Atc for training </li>

            </ul>


        </div>
    </div>

    {{/content}}

    {{/layout}}
