#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql'
cookbook 'database'
cookbook 'mysql2_chef_gem'
cookbook 'php'
cookbook 'apache2'
cookbook 'nodejs'
cookbook 'composer'
cookbook 'hostsfile'
cookbook 'memcached'
cookbook 'git'
cookbook 'openssl'
cookbook 'php-mcrypt', '~> 1.0.0'
cookbook 'java', '~> 1.39.0'